### ISSUE TITLE
Ability to adjust out of sync subtitles

### ISSUE THREAD

**Issue by meganugen** [pannal/Sub-Zero.bundle#254] opened 2017-03-09 06:06 UTC
Even though the match is a great one the subtitle can be a bit out of sync which is super frustrating.  Especially when the subtitle starts i.e. 500ms after the person speak in the film. There are 3rd party tools (i.e. SubShifter) where I can adjust this manually by uploading the srt-file and adjust the delay with + / - x.x seconds. Then I have do replace the bad srt-file with the new one and manually update Plex and wait. Since I want Sub-Zero to be my "one-stop-shop" for all my subtitles needs I would very much like to have this ability build in Sub-Zero. 

Fact: For every out of sync subtitle a bunny dies somewhere in the world, did you know that?

**Comment by pannal** [comment] 2017-03-09 08:53
You may first want to try to set your scores right. The defaults aren't necessarily 100% perfect.

Try using 116 for tv series and 46 for movies. That way you'll get less subtitles but more sync ones.


Other than that: #201 will take your suggestions :)

**Comment by meganugen** [comment] 2017-03-09 15:38
Thank you, will try adjusting the scores. #201
<https://github.com/pannal/Sub-Zero.bundle/issues/201> has a pretty good
idea about what I wanted.. :)

2017-03-09 9:53 GMT+01:00 pannal <notifications@github.com>:

**Comment by pannal** [comment] 2017-03-09 17:32
Closing as duplicate of #201

**Closed by pannal** 2017-03-09 17:32 UTC
