### ISSUE TITLE
Addic7ed and Daredevil

### ISSUE THREAD

**Issue by joakim93** [pannal/Sub-Zero.bundle#246] opened 2017-02-27 19:41 UTC
Hi,
So the plugin won't match Marvels Daredevil to Daredevil on addic7ed. Saw another issue with the same thing #124 Should this work?
```2017-02-27 20:36:44,431 (8057b6800) :  WARNING (logger:36) - subliminal_patch.patch_providers.addic7ed: Series not found in show ids, attempting search
2017-02-27 20:36:47,017 (8057b6800) :  WARNING (logger:36) - subliminal_patch.patch_providers.addic7ed: Show id not found: no suggestion
2017-02-27 20:36:47,018 (8057b6800) :  ERROR (logger:36) - subliminal_patch.patch_providers.addic7ed: No show id found for u"Marvel's Daredevil" ({'country': None, 'year': None})
2017-02-27 20:36:48,689 (8057b6800) :  ERROR (logger:36) - subliminal_patch.patch_providers.tvsubtitles: No show id found for u"Marvel's Daredevil" ({'year': None})
2017-02-27 21:19:18,675 (80a823000) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x80c1c4668>
2017-02-27 21:19:43,522 (80bf89800) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x80c1c4668>
2017-02-27 21:19:43,712 (802731000) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x80c1c4668>
2017-02-27 21:19:46,437 (8056a7000) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x80c1c4668>
2017-02-27 21:24:28,404 (8057b6800) :  ERROR (model:205) - Cannot read model from /var/db/plexdata/Plex Media Server/Metadata/TV Shows/0/569b0758c70f1ceb25d81bd5ffa5afd6ebdb138.bundle/Contents/com.plexapp.agents.subzero
2017-02-27 21:24:31,086 (8057b6800) :  WARNING (logger:36) - subliminal_patch.patch_providers.addic7ed: Series not found in show ids, attempting search
2017-02-27 21:24:31,087 (8057b6800) :  ERROR (logger:36) - subliminal_patch.patch_providers.addic7ed: No show id found for u"Marvel's Daredevil" ({'country': None, 'year': None})
2017-02-27 21:24:32,281 (8057b6800) :  ERROR (logger:36) - subliminal_patch.patch_providers.tvsubtitles: No show id found for u"Marvel's Daredevil" ({'year': None})
2017-02-27 21:24:33,097 (8057b6800) :  WARNING (logger:36) - subliminal_patch.patch_providers.addic7ed: Series not found in show ids, attempting search
2017-02-27 21:24:33,097 (8057b6800) :  ERROR (logger:36) - subliminal_patch.patch_providers.addic7ed: No show id found for u"Marvel's Daredevil" ({'country': None, 'year': None})
2017-02-27 21:24:33,664 (8057b6800) :  ERROR (logger:36) - subliminal_patch.patch_providers.tvsubtitles: No show id found for u"Marvel's Daredevil" ({'year': None})
2017-02-27 21:24:38,779 (8057b6800) :  CRITICAL (agentkit:1067) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 1.4.19.882)', called with guid 'com.plexapp.agents.thetvdb://281662?lang=en' (most recent call last):
  File "/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 213, in update
    save_subtitles(scanned_video_part_map, downloaded_subtitles)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 163, in save_subtitles
    save_subtitles_to_file(downloaded_subtitles)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 142, in save_subtitles_to_file
    chmod=config.chmod, forced_tag=config.forced_only, path_decoder=force_unicode)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_api.py", line 142, in save_subtitles
    os.chmod(subtitle_path, chmod)
OSError: [Errno 1] Operation not permitted: "/mnt/tvshows/Marvel's Daredevil/Season 02/Marvel's Daredevil - S02E04 - Penny and Dime WEBDL-1080p skgtv.en.srt"´´´

**Comment by pannal** [comment] 2017-02-27 20:44
There are problems with matching some shows still. This will be fixed with 1.5 and the new subliminal. 

You have a bigger issue than that, though. It finds a subtitle for you but can't save it because of permission errors. 

I'd fix that, otherwise sz doesn't work. Please have a look at the wiki on to how to do that.

**Comment by joakim93** [comment] 2017-02-27 20:50
Okay nice, Yeah I saw that error. But I think it is because I manually did download the subtitle from addic7ed and put it in the folder. Maybe i hadn't changed the permissions on that file when SZ did its refresh. Anyways SZ is working as it should.

**Comment by pannal** [comment] 2017-02-27 20:52
Ok. I'm closing this now as the issue is known but before 1.5 is ready it's not fixable. 

Thank you for reporting it!

**Closed by pannal** 2017-02-27 20:52 UTC
