### ISSUE TITLE
Sub-zero not working for months after PMS updates.

### ISSUE THREAD

**Issue by jokurino** [pannal/Sub-Zero.bundle#781] opened 2022-02-13 12:46 UTC
I have the Latest Sub-zero.bundle installed in the plugins folder, Plex sees the plugin and sees it sitting in the Agents TAB. I can configure it and do everything with it. The problem is whenever I refresh my metadata or library it just doesn't download any subtitles anymore. It happened after I upgraded my library to the new version.

Anyone who can help me with the logs? Where I should start looking.

**Comment by pannal** [comment] 2022-02-13 14:06
Duplicate of #753

**Closed by pannal** 2022-02-13 14:06 UTC
