### ISSUE TITLE
Automatically delete leftover subtitles option deletes .txt files

### ISSUE THREAD

**Issue by Gittun** [pannal/Sub-Zero.bundle#432] opened 2018-02-06 14:50 UTC
I noticed after installing and configuring this plugin that my torrent client started complaining about I/O errors. At first I thought my drive was failing, but I noticed it was just the information text files sometimes included with (public) torrents.

Because of the timing I decided to check the sub-zero logs (after increasing log level) and I get things like this if I update metadata:

> 2018-02-06 15:45:55,706 (1230) :  INFO (logkit:16) - Removing leftover subtitle: T:\series\altered carbon\Altered.Carbon.S01.720p.NF.WEBRip.DDP5.1.x264-NTb[rartv]\RARBG.txt

Now, I personally don't really care about the file, but it messes with the ability to keep seeding the torrents.

Is this setting supposed to delete .txt files? If so, is it maybe possible to make it ignore files that are not a subtitle format with a setting I missed?

**Comment by pannal** [comment] 2018-02-08 09:34
Hey,

.txt is technically a subtitle format. The issue is fixed in the upcoming 2.5 version, though.

**Comment by Gittun** [comment] 2018-02-08 11:49
Ahhh, I wasn't aware of that, this makes a lot more sense now.

I will keep the setting off till the release, then.

**Comment by pannal** [comment] 2018-02-08 13:06
Hmm. Now that I think about it: If you had SZ configured to use a subtitle directory, such as "subs", it would be logical for SZ not to clean anything not inside the subs folder. Currently it'd also clean the folder of the media file itself, regardless of the subtitle folder setting.

That's a different ticket, though.

**Closed** 2018-02-12 13:27 UTC
Labels: 2.0, enhancement
