### ISSUE TITLE
downloading subtitles, even though I already have embedded subs

### ISSUE THREAD

**Issue by ccutrer** [pannal/Sub-Zero.bundle#263] opened 2017-04-12 23:09 UTC
I have MKV files with PGS subs embedded in them (blu-ray rips). In my settings, I have `Scan: include embedded subtitles (in the media file (MKV/MP4), don't download if existing)` checked. This has been working fine for months, but about two weeks ago I started noticing it was still downloading external subs for newly added items. I'm guessing a regression in a recent release?

**Comment by pannal** [comment] 2017-04-13 13:47
It's a side-effect of the recent core changes, yes. Exotic subtitles (everything else than srt and ass/ssa) are currently not evaluated. This will be fixed.

Duplicate of #238

**Closed by pannal** 2017-04-13 13:47 UTC

**Comment by pannal** [comment] 2017-04-13 16:45
#264
