### ISSUE TITLE
Cannot read model from

### ISSUE THREAD

**Issue by altendorfme** [pannal/Sub-Zero.bundle#405] opened 2017-12-12 00:33 UTC
Hi, 

A problem is appearing in the log: ERROR (model:205) - Cannot read model from, full log attached.

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1549848/com.plexapp.agents.subzero.log)

Thank you for your work!

**Update:** (Debug mode)
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1549900/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment] 2017-12-12 10:59
Yeah, that's not an issue. The plugin model data for that media seems to be empty - it won't affect the usability.

**Comment by altendorfme** [comment] 2017-12-12 17:02
Another doubt, unrelated to the initial problem.
The plugin always lists that all files are without subtitles:

![untitled-1](https://user-images.githubusercontent.com/1530032/33897718-5d18fd62-df4d-11e7-8c18-8b46d6b1289e.jpg)

I've already used Refresh All Metatags and re-ordered the agents, but no found solution.

Thanks!

**Comment by pannal** [comment] 2017-12-12 17:05
Interesting, can you attach a log from after hitting "find recent items with missing subtitles"?

Also could you make a screenshot of your SZ preferences?

**Comment by altendorfme** [comment] 2017-12-12 19:57
Log:
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1553087/com.plexapp.agents.subzero.log)

SZ Settings:
![untitled-1](https://user-images.githubusercontent.com/1530032/33905441-cf9f2128-df65-11e7-9214-09a3d2418365.jpg)

**Comment by pannal** [comment] 2017-12-13 09:21
Hey,

I don't see any "usage" inside that log file. Can you navigate to the items with missing subtitles menu, hit the "Find" button, wait 5 minutes, then re-post the log?

**Comment by altendorfme** [comment] 2017-12-13 17:16
Okay!

[com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/1556370/com.plexapp.agents.subzero.zip)

**Comment by pannal** [comment] 2017-12-13 22:15
Hmm, I still don't see DEBUG information inside your log files. Please set "How verbose should the logging be?" to "DEBUG" (the part furthest down on your screenshot).

Also it seems like Sub-Zero [isn't enabled for any of your libraries](https://github.com/pannal/Sub-Zero.bundle/wiki/Agent-configuration).

In addition to that there seems to be a problem with your storage - what do you use as storage? I'm seeing a bunch of input/output filesystem errors in the logs.

**Comment by altendorfme** [comment] 2017-12-13 22:33
Okay.
Movies Library:
![untitled-1](https://user-images.githubusercontent.com/1530032/33965475-25cb5890-e043-11e7-86c6-5d4e21979f4a.png)

I'm clean all subzero logs, change to debug, restart plexmediaserver and force scan subtitles.
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1557351/com.plexapp.agents.subzero.log)

My storage is a external usb3 drive, mounted via fstab:
`UUID=XXX /media/storage auto rw,auto,users,exec,nls=utf8,fmask=000,umask=000,gid=1000,uid=1000    0   0`

Thank you for the patience!

**Comment by pannal** [comment] 2017-12-13 22:39
That log looks completely fine to me. No errors in there, it found all pt-BR subtitles as it seems.
Can you try to re-create the issue of your first screenshot, then post the log?

**Comment by altendorfme** [comment] 2017-12-13 22:50
![untitled-1](https://user-images.githubusercontent.com/1530032/33966558-239e8886-e047-11e7-9832-ac7901cabed0.png)

I went to the movie, click on Refresh and this is the log:
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1557394/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment] 2017-12-13 22:59
Was the subtitle downloaded from Sub-Zero?

Also do you have `Don't search for subtitles if they already exist on the filesystem (metadata/filesystem)` enabled?

**Comment by pannal** [comment] 2017-12-14 00:54
Hmm weird, I can't reproduce it locally.

**Comment by altendorfme** [comment] 2017-12-14 01:46
This?
![capture](https://user-images.githubusercontent.com/1530032/33971459-a0c8f068-e05f-11e7-861f-ab64480ac531.PNG)
No.

If I need it, I can give you access to the plex.

**Comment by pannal** [comment] 2017-12-14 02:46
No, I mean exactly this: `Don't search for subtitles if they already exist on the filesystem (metadata/filesystem)?` It's right below the one you just posted.

**Comment by altendorfme** [comment] 2017-12-14 15:35
Oww sorry!

![capture](https://user-images.githubusercontent.com/1530032/34000053-5beb8838-e0d3-11e7-9f17-8884c0f1de06.PNG)

Should I disable?
I understood that this would find the subtitles in the filesystem, it would save, but it would not look in the indexers (subtitles, opensub)

**Comment by pannal** [comment] 2017-12-14 15:59
Hm, no, keep it enabled. 

Was the subtitle for `It (2017) WEBDL-720p-SHITBOX.avi` downloaded by Sub-Zero or was it there, before?

**Comment by altendorfme** [comment] 2017-12-14 16:03
Before.

**Comment by pannal** [comment] 2017-12-14 16:09
Ah OK, then that's intended behaviour.

SZ currently can only manage subtitles it itself downloaded, not pre-existing ones. That's why you don't see the same menu.

This will hopefully be fixed with version 2.1, which is upcoming.

**Closed by pannal** 2017-12-14 16:09 UTC
