### ISSUE TITLE
SearchAllRecentlyAddedMissing: TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by sephrat** [pannal/Sub-Zero.bundle#462] opened 2018-03-09 19:56 UTC
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1798226/com.plexapp.agents.subzero.log)

```
2018-03-09 20:49:32,840 (200e0fc450) :  ERROR (scheduler:132) - Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing: Traceback (most recent call last):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scheduler.py", line 130, in run_task
    task.run()
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 499, in run
    Thread.Sleep(PROVIDER_SLACK)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 113, in scan_videos
    skip_hashing=skip_hashing)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 84, in scan_video
    only_one=config.only_one)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subzero/video.py", line 25, in set_existing_languages
    only_one=only_one).values())
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 591, in search_external_subtitles
    only_one=only_one))
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 519, in _search_external_subtitles
    for entry in scandir(dirpath):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/scandir.py", line 543, in scandir_python
    opendir_path = path.encode(file_system_encoding)
TypeError: encode() argument 1 must be string, not None

```

Manual download works fine.
Plex is on an Nvidia Shield TV connected to a NAS.

**Comment by pannal** [comment] 2018-03-13 15:59
Duplicate of #461

**Comment by pannal** [comment] 2018-03-13 16:00
#441

**Closed by pannal** 2018-03-13 15:59 UTC
Labels: invalid
