### ISSUE TITLE
Not downloading any subtitles for newly added items automatically

### ISSUE THREAD

**Issue by tknikolov** [pannal/Sub-Zero.bundle#236] opened 2017-02-07 15:50 UTC
Hello @pannal ,

I posted this in the Plex forum but was guided to post a ticket here.. so there it is!

First of all - awesome plugin! I've been using it for couple of months now and I can't thank you enough!

The difficulty I'm having is Sub-Zero would not download subtitles for my TV Episodes (or movies) after the initial download (right after the episode is added into plex). When I refresh the series manually, then it downloads the newly found subs. But there's an option in the menu to search for new subtitles for your recent content - which seems exactly what I'm looking for - however nothing happens when it's ticked. Here's what I get from the subzero logs file:

```
2017-02-07 15:44:10,541 (7fb413fff700) :  DEBUG (background:139) - Scheduler: Not sending signal updated_metadata to task FindBetterSubtitles, because: not running
2017-02-07 15:44:10,542 (7fb413fff700) :  DEBUG (background:139) - Scheduler: Not sending signal updated_metadata to task SearchAllRecentlyAddedMissing, because: not running
```

I had to enable DEBUG to see anything in the log. However from that log I cannot really tell what's "not running".

Can you please point me into the right direction? I must be doing something wrong. Let me know if even more log files are needed.

Much appreciated!

Tenko

**Comment by pannal** [comment] 2017-02-07 16:09
Hey,

I think actually you're good. The logfile doesn't show anything bad. The DEBUG info just says: the current subtitle-search did not originate from the scheduler, so don't signal the scheduler.

The series/movies you're having problems with, are they specifically new? It may well be, that there isn't a subtitle available right after it's added, which meets the cutoff (the configured scores). Sub-Zero runs a SearchForMissingSubtitles task periodically, as well as FindBetterSubtitles.

Could you get me a log file of such a newly added item, right after it's been added? Sub-Zero should have been triggered and I can see why you're not getting any subtitles for those items.

**Comment by tknikolov** [comment] 2017-02-07 17:31
Hey, thanks for the speedy response! 

Indeed you are right. It's only brand new shows I'm referring to - a couple of them. When a new episode airs, I download it, add it to Plex and I've set it to search for 2 languages - EN and BG. EN Usually ships with the episode, so I don't know if Sub-Zero downloads anything, but BG never appears alone. I have to refresh manually in order to get it - and when I do I now know it's been there, just not downloaded.

Sometimes an episode would not have any subtitles again until I hit refresh. Very strange. I'll try to get you the logs next time an ep airs. 

I've set the scheduler in settings to run every one hour and to consider recent for 2 weeks back.

Thanks again!

**Comment by tknikolov** [comment] 2017-02-08 08:43
Okay, here's a log file for one episode of Supergirl, downloaded yesterday. It had downloaded EN subs, but no BG. Today I clicked refresh and BG appeared. 

[com.plexapp.agents.subzero.log.1.zip](https://github.com/pannal/Sub-Zero.bundle/files/760091/com.plexapp.agents.subzero.log.1.zip)

**Comment by pannal** [comment] 2017-02-08 12:36
In the first log, have you just added DC Legends of Tomorrow? I'm trying to determine whether all that log content and searching for subtitles is automatic upon adding or triggered by you.

As for Supergirl: the subtitle was available 21 hours ago (GMT+1). Can you make something of that information?

Yes, in DEBUG mode those logs rotate like hell. You could always zip up all of the logs (the rotated ones also).

The New Girl EN example: the subtitle was added to addic7ed on 00:21:34 (i guess GMT).

To further approach this: try moving one episode of anything out of the way and let Plex notice its absence. Also delete the subtitles. Then move it back in - let Plex notice. Then see if SZ downloads subtitles for that media file and/or give me the logs.

**Comment by pannal** [comment] 2017-02-08 12:37
Also please press `Log the plugin's scheduled tasks state storage` in the `Advanced` menu and post the log.

**Comment by pannal** [comment] 2017-02-08 13:14
You can just do those things in order and zip up the logs (all of the rotated ones aswell), I'll have a look.

But yeah, I'm suspecting something's wrong with the searchrecentlyaddedmissing task. Or the scheduler itself. Did you restart the PMS recently?

**Comment by tknikolov** [comment] 2017-02-08 14:39
Yes, I've just added Legends of Tomorrow too. I didn't use it as an example, just because I thought Supergirl and the New Girl were enough. 

So from what you've written, both subtitles were available for at least 10-12 hours before I downloaded them manually but they were available _after_ I've added the series to Plex. It kinda confirms my theory that if subs become available after the episode has been added, it would never download them by itself, only by manual refresh.

I've done what you requested in two steps:

1) I clicked the Log the plugin's scheduled tasks in Advanced Channel menu. Then I removed Supergirl and its subs and re-added it. This time the Subs were downloaded accordingly, because they existed at the time of adding the ep. Full zip of all logs of this - here:

[supergirl.zip](https://github.com/pannal/Sub-Zero.bundle/files/760884/supergirl.zip)

2) Then I waited some more time.. and went and clicked to "Search for missing subs". Then waited for a couple of minutes (nothing happened, according to the logs) and zipped all the logs again , which is here:

[refresh.zip](https://github.com/pannal/Sub-Zero.bundle/files/760888/refresh.zip)

I have restarted PMS last Sunday. Before that I have been restarting it probably once a month... not because it was needed, but just in case. But this feature never worked for me. Is there a way I can prove if the scheduler is working or not?

Thanks!

**Comment by tknikolov** [comment] 2017-02-08 14:58
Two more things I've just noticed - 

1) In Channels -> Sub Zero -> Below "Search for missing subs" - It says the scheduler has _never_ been run

![screen shot 2017-02-08 at 4 53 16 pm](https://cloud.githubusercontent.com/assets/25615485/22742377/3476a906-ee1f-11e6-863f-3ad571436454.png)

2) Again In Channels -> Sub Zero -> Items with missing subtitles - It does not show anything but "refresh here". 

Don't know if (2) is related, just found it strange and hence mentioning it.

**Comment by pannal** [comment] 2017-02-08 15:28
Uh, OK. Two things:
Please go to the advanced menu and trigger the reset for the internal task storage.
Then could you shut down your PMS and see if there are any zombie processes of it left (and kill them)?

Then restart your PMS.

**Comment by pannal** [comment] 2017-02-08 15:37
After we've confirmed nothing else is wrong, we'll have to do it the hard way. With a manual installation of SZ and some debugging :)

**Comment by cvium** [comment] 2017-02-08 19:34
I'm experiencing the same issue of the scheduler not running.

**Comment by pannal** [comment] 2017-02-08 20:53
@cvium I'll need logs from you, too. Please attach them or put them on pastebin.

**Comment by pannal** [comment] 2017-02-08 20:58
Also those logs from right after a plex server restart please.

**Comment by tknikolov** [comment] 2017-02-09 10:17
Okay, I've reset for the internal task storage. Then stopped PMS. Looked for Zombies, but nothing was there, just PlexPy, which is a side daemon I run. 

I restarted Plex. No change in status quo though, lots of new series today, none of them downloaded subs by itself. 

I think I'm currently running latest stable from the repo. At some point for some time I used latest stable + this patch, that has a pull request towards sub zero:

https://github.com/pannal/Sub-Zero.bundle/pulls

But right now I'm running a clean state and it doesn't work. How do we go about manual install/debug? 

And is there a way around this.. Like calling "Search for missing subs" from the cli and cronjob it?

**Comment by cvium** [comment] 2017-02-09 10:33
This is the tasks state storage after PMS restart:
```
2017-02-09 11:28:21,200 (7fa57e7fc700) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2017-02-09 11:28:21,200 (7fa57e7fc700) :  DEBUG (runtime:924) - Response: [200] SubFolderObjectContainer, 2935 bytes
2017-02-09 11:28:21,281 (7fa57e7fc700) :  DEBUG (runtime:717) - Handling request GET /video/subzero/storage/log?randomize=1486635985&key=tasks
2017-02-09 11:28:21,289 (7fa57e7fc700) :  DEBUG (runtime:814) - Found route matching /video/subzero/storage/log
2017-02-09 11:28:21,296 (7fa57e7fc700) :  DEBUG (storage:114) - {'AvailableSubsForItem': {'data': {}, 'last_run': None, 'last_run_time': None}
,
 'DownloadSubtitleForItem': {'data': {'missing_subtitles': []},
                             'last_run': None,
                             'last_run_time': None},
 'FindBetterSubtitles': {'data': {},
                         'last_run': datetime.datetime(2016, 12, 26, 9, 53, 40, 939548),
                         'last_run_time': None},
 'MissingSubtitles': {'data': {},
                      'last_run': datetime.datetime(2016, 12, 17, 13, 17, 38, 606543),
                      'last_run_time': None},
 'SearchAllRecentlyAddedMissing': {'data': {'missing_subtitles': []},
                                   'last_run': datetime.datetime(2016, 12, 26, 10, 2, 47, 467136),
                                   'last_run_time': datetime.timedelta(0, 0, 199)},
 'queue': [(('SearchAllRecentlyAddedMissing',), {}),
           (('SearchAllRecentlyAddedMissing',), {})],
 'searchAllRecentlyAddedMissing': {'last_run': datetime.datetime(2016, 11, 21, 18, 23, 58, 385881),
                                   'last_run_time': datetime.timedelta(0, 0, 107)}}
2017-02-09 11:28:21,303 (7fa57e7fc700) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2017-02-09 11:28:21,303 (7fa57e7fc700) :  DEBUG (runtime:924) - Response: [200] SubFolderObjectContainer, 2935 bytes
```
This is after resetting task storage
```
2017-02-09 11:31:13,848 (7fa57e7fc700) :  DEBUG (storage:114) - {'AvailableSubsForItem': {'data': {}, 'last_run': None, 'last_run_time': None
,
 'DownloadSubtitleForItem': {'data': {},
                             'last_run': None,
                             'last_run_time': None},
 'FindBetterSubtitles': {'data': {}, 'last_run': None, 'last_run_time': None},
 'MissingSubtitles': {'data': {}, 'last_run': None, 'last_run_time': None},
 'SearchAllRecentlyAddedMissing': {'data': {},
                                   'last_run': None,
                                   'last_run_time': None},
 'queue': []}
```
Nothing happens when I click on "Search for missing subtitles". This is the log it produces:
```
2017-02-09 11:33:07,503 (7fa57e7fc700) :  DEBUG (runtime:717) - Handling request GET /video/subzero/missing/refresh?randomize=1486636361
2017-02-09 11:33:07,510 (7fa57e7fc700) :  DEBUG (runtime:814) - Found route matching /video/subzero/missing/refresh
2017-02-09 11:33:07,770 (7fa57e7fc700) :  INFO (datakit:131) - Saved the dictionary file
2017-02-09 11:33:07,772 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents'
2017-02-09 11:33:07,826 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents/com.plexapp.agents.none/co
nfig/1'
2017-02-09 11:33:07,862 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents/com.plexapp.agents.none/co
nfig/2'
2017-02-09 11:33:07,903 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents/com.plexapp.agents.imdb/co
nfig/1'
2017-02-09 11:33:07,937 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents/com.plexapp.agents.thetvdb
/config/2'
2017-02-09 11:33:07,974 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents/com.plexapp.agents.themovi
edb/config/1'
2017-02-09 11:33:08,010 (7fa57e7fc700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/agents/com.plexapp.agents.themovi
edb/config/2'
2017-02-09 11:33:08,047 (7fa57e7fc700) :  DEBUG (config:229) - I'm enabled for: ['Movies', 'TV Shows']
2017-02-09 11:33:08,057 (7fa57e7fc700) :  DEBUG (runtime:88) - Sending packed state data (2927 bytes)
2017-02-09 11:33:08,058 (7fa57e7fc700) :  DEBUG (runtime:924) - Response: [200] SZObjectContainer, 2963 bytes
```

**Comment by pannal** [comment] 2017-02-09 12:40
Please don't inline the logs directly. I explicitly asked for attaching/pastebin..

**Comment by pannal** [comment] 2017-02-09 12:44
So @cvium you are using the official channel version I guess? That's odd, @tknikolov uses a manual installation.

I'll put together a test build for you two. @tknikolov it's possible to call SZ functions from the outside via the API, but that's exactly the same you do when using the channel menu in a Plex client. As long as the scheduler doesn't work, that won't work either. Is your `Info.plist` already set to "PlexPluginDevMode`=`1`?

**Comment by cvium** [comment] 2017-02-09 12:47
Currently using 1.4.19.866

**Comment by pannal** [comment] 2017-02-09 12:50
@cvium again: Are you using a manual installation or did you install the plugin using the plex channel repository?

**Comment by cvium** [comment] 2017-02-09 12:56
Dunno, it's been so long. Is there a way to check? It's probably the channel repo.

**Comment by pannal** [comment] 2017-02-09 12:58
If you haven't downloaded a zip file and unpacked it for Sub-Zero during the last few days, the upgrade has been automatic and you're using the official channel version.

**Comment by cvium** [comment] 2017-02-09 13:03
I haven't touched the Sub-Zero installation since I installed it last year.

**Comment by pannal** [comment] 2017-02-09 14:12
OK I've just cleaned my whole Sub-Zero installation and installed it from the official channel repository. The scheduler works.

Something must've gone wrong with either the configuration or the upgrade process.

Preparing a debug build.

**Comment by pannal** [comment] 2017-02-09 14:24
OK, the debug build [is here](https://github.com/pannal/Sub-Zero.bundle/archive/scheduler_debug.zip). Please uninstall Sub-Zero using the channel repository, delete any leftovers in the Plug-Ins folder of SZ, unpack the zip into the Plug-Ins folder and rename the resulting folder to Sub-Zero.bundle.

Then start your PMS, wait a minute, stop it, and attach the log files, please.

**Comment by cvium** [comment] 2017-02-09 14:41
Hope I did it correctly.

[com.plexapp.agents.subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/763964/com.plexapp.agents.subzero.log.txt)

**Comment by pannal** [comment] 2017-02-09 14:44
OK @cvium I know why the scheduler isn't running. You've got insufficient permissions on one of your library folders (it is displayed in the channel menu as well):
`2017-02-09 15:38:44,480 (7fb44103a700) :  ERROR (__init__:65) - Insufficient permissions on library Movies, folder: /media/media-500/movies`

Can you please fix that and see if that resolves the problem?

**Comment by cvium** [comment] 2017-02-09 14:48
Seems like it's running now, but that's probably something that should be fixed. It had insufficient permissions because I disconnected the drive, but it still has "permissions" for the other three drives.

**Comment by pannal** [comment] 2017-02-09 14:49
Yeah I've had a hard-bailout on the whole system if a permission was wrong, so the scheduler run never got called. Fixed in develop-1.4.

You can go back to the official channel version or use develop-1.4 until it gets pushed to the official channel.

@tknikolov how about you?

**Comment by cvium** [comment] 2017-02-09 15:05
Alright, sounds good. I'll just go back to the official version. I've just been lazy about removing the folder from the library.

**Comment by paceto256** [comment] 2017-02-09 17:06
Here is the log by the server of @tknikolov

[debug.txt](https://github.com/pannal/Sub-Zero.bundle/files/764420/debug.txt)

**Comment by pannal** [comment] 2017-02-09 17:12
Ah, nice. Same problem. Insufficient permissions on library `Kids EN Audio`.

@tknikolov If you can live another couple of days without the scheduler, just wait for my next 1.4 release. If not, you can pop in [develop-1.4](https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip), it has that "feature" "fixed". Although you should probably just fix the permissions on that library folder.

**Closed by pannal** 2017-02-09 17:12 UTC

**Comment by pannal** [comment] 2017-02-15 14:39
I don't know whether this was a good idea.

I'm already getting users with wrong permissions who spam the shit out of the providers. Before that was not possible because nothing worked and they had to come here. Now nothing works for them but the additionally spam the providers :D
