### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ready_for_display'

### ISSUE THREAD

**Issue by SunMar** [pannal/Sub-Zero.bundle#249] opened 2017-03-05 11:36 UTC
Hi,

When I try to go to the Sub-Zero I get an error "This channel is not responding". When I check the com.plexapp.agents.subzero.log I see the following:

> 2017-03-05 12:27:55,437 (35a0) :  CRITICAL (core:574) - Exception (most recent call last):
>   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-03e4cfa35\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
>     result = f(**d)
>   File "C:\Users\SunMar\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\interface\menu.py", line 118, in fatality
>     if task.ready_for_display:
> AttributeError: 'NoneType' object has no attribute 'ready_for_display'

I've already tried uninstalling and re-installing the channel. When I try to reset the channel the same error occurs and I see "There was a problem resetting this channel.".

The Info.plist in the plugin directory says I'm using version 1.4.22.898, the VERSION file says "5e45247 (Thu Mar 02 15:54:16 UTC 2017)". I'm running Plex Media Server 1.4.3.3433.

**Comment by pannal** [comment] 2017-03-06 13:42
Duplicate of #250

**Closed by pannal** 2017-03-06 13:42 UTC
