### ISSUE TITLE
Sub-Zero not considering new "Plex Movie" agent libraries

### ISSUE THREAD

**Issue by xxxxxaaaaaaaannnn** [pannal/Sub-Zero.bundle#770] opened 2021-08-10 14:19 UTC
Hello,

When running Sub-Zero, I noticed that the libraries with the (new) agent "Plex Movie" are not considered while the ones with "The Movies Database" (or others) are :

Logs : 
DEBUG (config:698) - I'm enabled for: ['Anime', '_downloads']

After I changed _downloads library to "Plex Movie": 
DEBUG (config:698) - I'm enabled for: ['Anime']

Any idea ?

**Comment by pannal** [comment] 2021-08-10 14:26
Duplicate of #753

**Closed by pannal** 2021-08-10 14:26 UTC
Labels: duplicate, cantfix, Ask Plex Inc., 2.6
