### ISSUE TITLE
Nordic character "å" becomes "Í" 

### ISSUE THREAD

**Issue by meganugen** [pannal/Sub-Zero.bundle#252] opened 2017-03-08 17:11 UTC
On most swedish subtitles beeing added by SubZero the nordic character "å" is being showed as "Í".

i.e. "Du är från Isnationen." will show up as "Du är frÍn Isnationen.".

![screenshot](https://cloud.githubusercontent.com/assets/26282403/23714670/61e36160-042a-11e7-97e8-ddbb3e83d43f.PNG)

**Comment by pannal** [comment] 2017-03-08 18:45
Are you sure this is not related to or a duplicate of #205 ?

**Comment by meganugen** [comment] 2017-03-08 19:30
Sorry. Its exactly that problem. I wish there was a script i could run
automatically to to replace the bad character to "å".

ons 8 mars 2017 kl. 19:45 skrev pannal <notifications@github.com>:

**Comment by pannal** [comment] 2017-03-08 22:18
I can add that as a feature later.

**Comment by ukdtom** [comment] 2017-03-09 01:19
That is indeed a great idea, since a lot of subs in the "Sphere" are badly converted into utf-8.

Now to add to this, I think that @pannal when dev on this starts, should create a post in the forums, asking people for language dependent info about the most spread chars been bad/correct

Like a file named `correct.se`:
`{ 'Í':'a'}`

If making such a post, I'll make it pinned for a while ;-)

/T

**Comment by pannal** [comment] 2017-03-09 08:56
I was thinking about making a replacement "list" (text field) setting, where one could add his own mapping.

Problem is, PMS doesn't like unicode in settings as far as I can remember.

**Comment by ukdtom** [comment] 2017-03-09 20:01
Thus why I suggest a json file for each language, that's hard coded but can be edited.
If the community creates the jsons, I think all would be okay

**Comment by pannal** [comment] 2017-03-09 20:02
That's a nice idea.

**Comment by pannal** [comment] 2017-05-12 23:34
This may be fixed in 2.0 with default subtitle modification OCR fixes

**Closed by pannal** 2017-05-12 23:34 UTC
Labels: enhancement

**Comment by subzeroo1** [comment] 2017-09-16 11:06
I assumes swe_OCRFixReplaceList was supposed to fix this problem?

Still have issues with Å showing as Í. I added these lines to swe_OCRFixReplaceList but it made no difference.
	<WordPart from="Í" to="å" />
	<WordPart from="ĺ" to="å" />
