### ISSUE TITLE
Embedded Subtitle

### ISSUE THREAD

**Issue by trox88** [pannal/Sub-Zero.bundle#678] opened 2019-09-28 11:48 UTC
Hello,

First of all I'm very gratefull for you work @pannal , just keep it up, thank you!

Sorry for my poor English (I'm hungarian), if you don't know everything what I want to ask.
------------------------------------------------------------------------------------------

I'm using SZ for 2 thing:

1, Automatically download subtitles (Hungarian) for my new episodes of series (Lang: english).
This works great, I dont really want to change anyithing.

2, Extract embedded subtitle from movies or series.
My problame is when there is a new movie in my library SZ doesn't extract it automatically, the only way I can do this with manual extract.

let me show you an example with Aladdin movie:

![SZ1](https://user-images.githubusercontent.com/55915414/65815717-8ec3a600-e1f3-11e9-843c-093cbe427694.PNG)
![SZ2](https://user-images.githubusercontent.com/55915414/65815720-984d0e00-e1f3-11e9-8841-bb37c410b16f.PNG)
![SZ3](https://user-images.githubusercontent.com/55915414/65815721-9c792b80-e1f3-11e9-9b13-5b4c7e265d28.PNG)
![SZ4](https://user-images.githubusercontent.com/55915414/65815726-9f741c00-e1f3-11e9-90a0-e87fbd0fa7cc.PNG)

This movie includes Hungarian language also, that's why I only need just the embedded forced Hungarian subtitle with default settings.

Can SZ handle this option? : If there is a movie or series episode without my choosen language (Hungary), so it can be English, Danish, German....etc, automatic extract just embededd hungarian subtitle (not forced) and after that if it not included, search on web.
But if the movie or series episode also have Hungarian language next to english or others, only extract embedded hungarian forced subtitle with default configuration (don't want to download, only use embedded) and do all this things automatically if a new movie arrives in the library.

Here is my setting to see what is wrong in my setup. Thank you for help!

![SZ5](https://user-images.githubusercontent.com/55915414/65815976-86209f00-e1f6-11e9-9a93-13aa39d712e1.PNG)
![SZ6](https://user-images.githubusercontent.com/55915414/65815977-86209f00-e1f6-11e9-95e4-9ece37bf75da.PNG)
![SZ7](https://user-images.githubusercontent.com/55915414/65815978-86209f00-e1f6-11e9-9d49-2b6127970275.PNG)
![SZ8](https://user-images.githubusercontent.com/55915414/65815979-86209f00-e1f6-11e9-9152-fe42848a30f8.PNG)
![SZ9](https://user-images.githubusercontent.com/55915414/65815980-86209f00-e1f6-11e9-9c72-88427996bf15.PNG)
![SZ10](https://user-images.githubusercontent.com/55915414/65815981-86b93580-e1f6-11e9-89ca-5d7251efca34.PNG)

**Comment by pannal** [comment] 2019-10-05 01:59
Your interface is all set to Hungarian, which I can't read. There will be a couple of issues fixed with the next release regarding embedded subs. If this issue persists after the next release, please reopen this ticket and explain what the issue is.

**Closed by pannal** 2019-10-05 01:59 UTC

**Comment by trox88** [comment] 2019-10-05 05:27
That's a good news. I'll wait it, and let's see what's going to change. If the issue presists, I'll make you English interface screenshots. Thanks for help.
