### ISSUE TITLE
Another provider - subscene, is it possible?

### ISSUE THREAD

**Issue by minihessel** [pannal/Sub-Zero.bundle#389] opened 2017-11-16 17:13 UTC
Subscene sometimes has subtitles that some providers do not, is it possible to add it? For example https://github.com/andy-pham/subscene-api

**Comment by pannal** [comment] 2017-11-16 17:18
Duplicate of #26 

Sorry.

**Closed by pannal** 2017-11-16 17:18 UTC

**Comment by minihessel** [comment] 2017-11-16 17:19
I should be the one saying sorry, I should've searched.

**Comment by pannal** [comment] 2017-11-16 17:21
#268 might interest you. though.

**Comment by pannal** [comment] 2018-01-05 22:05
I've taken another shot at SubScene in 2.1. [Please join the SZ beta](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes)!
