### ISSUE TITLE
Subzero went missing

### ISSUE THREAD

**Issue by penzinho** [pannal/Sub-Zero.bundle#574] opened 2018-09-17 08:14 UTC
Suddenly subzero went missing from the Plugins section. I can't access it any more, although it shows as installed. I've tried reinstalling it and rebooting the server and no luck.

![image](https://user-images.githubusercontent.com/17112029/45612146-5e82ec80-ba62-11e8-8217-d7b1f3abf366.png)

![image](https://user-images.githubusercontent.com/17112029/45612149-66429100-ba62-11e8-815a-25da933885a1.png)

[Plex Media Server Logs_2018-09-17_10-14-17.zip](https://github.com/pannal/Sub-Zero.bundle/files/2387739/Plex.Media.Server.Logs_2018-09-17_10-14-17.zip)

**Comment by ukdtom** [comment] 2018-09-17 11:41
https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q1-sub-zero-is-not-visible-among-the-channels

**Comment by pannal** [comment] 2018-09-17 13:00
Did you try to restart the PMS?

**Comment by penzinho** [comment] 2018-09-18 07:41
> https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q1-sub-zero-is-not-visible-among-the-channels

It doesn't work. Nothing happens after clicking gear icon.


> Did you try to restart the PMS?

Yup, multiple times. No luck.

I even tried uninstalling subzero, deleting subfolders in plugin folder and reinstalling but it hangs like shown on the pic below.

![image](https://user-images.githubusercontent.com/17112029/45671880-f2b68780-bb26-11e8-93b9-c1bf99658d89.png)

Do you need debug logs? :)

**Comment by ukdtom** [comment] 2018-09-19 22:00
Disable verbose logging, and use just debug logging
Then download logs as outlined here: https://github.com/pannal/Sub-Zero.bundle/wiki/Logs
The logs you uploaded are Plex logs only, and doesn't contain logs from 3.Party

**Comment by penzinho** [comment] 2018-10-10 19:37
It happened again on a new installation, I'll post logs tomorrow

**Comment by pannal** [comment] 2018-10-15 12:33
This might be related to your Radarr settings: `ConnectionError: HTTPConnectionPool(host='188.166.78.27', port=8989): Max retries exceeded with url: /api/system/status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f79af903d50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`

**Comment by pannal** [comment] 2018-10-26 13:00
This was an error on my side. When OpenSubtitles was the only enabled provider, and it was throttled, the plugin disabled itself. Will be fixed in 2.6.

**Comment by penzinho** [comment] 2018-11-04 18:04
Thanks a lot, glad if my bug report made smallest of differences.

I am trying developer branch 2.6 but it is still disabled. How can I manually re-enable it? Probably one true/false edit with nano but can't find it :)

**Comment by pannal** [comment] 2018-11-05 16:51
@penzinho are you sure you're using the develop version? Did you remove SZ, then stop the PMS, then added the develop-2.6 checkout? Can you confirm the 2.6 version from your agent list?

**Comment by penzinho** [comment] 2018-11-19 22:29
Manually removed the old version, stopped the PMS and manually added newest version...and still doesn't work.

It is not shown under installed plugins at all. I can get you any logs you need, please help me with this. I'd like to avoid reinstalling PMS and rescanning the db. Maybe we can chat on Discord to get this sorted out?

Thanks in advance

**Comment by pannal** [comment] 2018-11-20 11:32
@penzinho you can join the [SZ Slack](https://szslack.fragstore.net) for a chat. Also please attach your logs zipped.

**Closed** 2019-04-18 21:42 UTC
Labels: 2.6, bug, uncertain
