### ISSUE TITLE
Sub-Zero no longer compatible with latest Plex update!

### ISSUE THREAD

**Issue by Memzmt** [pannal/Sub-Zero.bundle#765] opened 2021-05-03 19:59 UTC
Please the creator i am calling out for help please oh please i know this plugin get no more updates but please make it work with the latest Plex updates and until you do i am never updating Plex again!

I know i am not alone in begging for support 🙏

Edit: I verified this by rolling back 2 versions of Plex then seeing the Sub-Zero plugin being shown again in agents and plugins tab as it is not visible in either tab when on latest update of Plex

**Comment by Jojesp** [comment] 2021-05-03 20:30
If we are lucky it might be a bug in plex and not by design. So lets hope that it gets fixed in the upcoming version.

**Comment by pannal** [comment] 2021-05-05 20:02
Duplicate of #764

**Closed by pannal** 2021-05-05 20:02 UTC
