### ISSUE TITLE
When opening channel, empty?

### ISSUE THREAD

**Issue by minihessel** [pannal/Sub-Zero.bundle#397] opened 2017-11-23 17:27 UTC
When opening the sub-zero channel(not settings) I just get an empty screen? 
<img width="1331" alt="screen shot 2017-11-23 at 18 26 37" src="https://user-images.githubusercontent.com/5398823/33184232-e06cec04-d07b-11e7-962c-7875a5d970b0.png">

**Comment by ukdtom** [comment] 2017-11-23 20:04
Duplicate of https://github.com/pannal/Sub-Zero.bundle/issues/395

**Closed by ukdtom** 2017-11-23 20:04 UTC
