### ISSUE TITLE
SubZero not downloading any subtitles

### ISSUE THREAD

**Issue by critaL** [pannal/Sub-Zero.bundle#476] opened 2018-03-26 13:32 UTC
Hey

I've been experiencing issues with subzero in that it fails to download any subtitles for the last week. Before that it's been working flawlessly, i love subzero.

I've attached the logs.
[Logs_180326_15-31-49.zip](https://github.com/pannal/Sub-Zero.bundle/files/1847995/Logs_180326_15-31-49.zip)

Seems to be a lot of errors with opensubtitles.

**Comment by pannal** [comment] 2018-03-26 14:13
duplicate of #475 :)

**Closed by pannal** 2018-03-26 14:13 UTC
