### ISSUE TITLE
Sometimes it downloads subtitles twice.

### ISSUE THREAD

**Issue by Nottt** [pannal/Sub-Zero.bundle#339] opened 2017-09-01 05:55 UTC
I have my files with duplicated subtitles for some reason, while some not. I don't know why, but at same time I have a big library to get subtitles and would like to waste the least possible of my daily limit so if anyone could help me find the issue !

My files are mostly year old content, looking at my history seems it's because of  (auto-better) but this makes no sense, as I doubt there are newer better subtitles a few days after I scan for years old content.

I will try to describe all I think that may matter about my system :+1: 

Ubuntu 16.04, with plex version 1.7.5.4035, latest subzero I believe, downloading English with PT-BR subtitles with OpenSubtitles.

SubZero settings : 

Enabled : 

- Scan: include embedded subtitles (in the media file (MKV/MP4), don't download if existing)
- Scan: include external subtitles (metadata/filesystem, don't download if existing)
- Scan : Loose
- Fix common errors
- Automatically delete leftover/unused (externally saved) subtitles
- Low impact mode (for remote filesystems)
- Scheduler: Periodically search for better subtitles : 12 Hours
- Scheduler: Periodically search for recent items with missing subtitles : 6 hours
- Saving as metadata

Bonus question if allowed : How to mass extract the already downloaded subtitles to another location ? 

Thanks for the software!

**Comment by pannal** [comment] 2017-09-01 07:11
> My files are mostly year old content, looking at my history seems it's because of (auto-better) but this makes no sense, as I doubt there are newer better subtitles a few days after I scan for years old content.

It's entirely possible that auto-better triggered for your older stuff. A provider might be unresponsive in the first run, or ignored you inside that first run because you're hitting provider limits. That provider is then responding again, after a couple of hours, when the auto-better task runs, and auto-better takes the now better subtitle.

Also make sure that there's only SZ subtitles in the media folder for a given media item, otherwise Plex may display duplicate subtitles.

> Bonus question if allowed : How to mass extract the already downloaded subtitles to another location ?
That's a bit more complicated and you'll need programming knowledge for that. SZ stores all of its downloaded subtitles (hopefully, there still seems to be the occasional bug) inside a separate per-item subtitle storage, together with meta information so stuff like auto-better works.

The location of the files is `Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.subzero\DataItems`. The files are gzipped json in UTF-8 format. You can use any programming language to open these and extract the UTF-8 subtitle content and do with it as you wish.

**Comment by Nottt** [comment] 2017-09-01 07:17
I don't have knowledge in any programming language :/ 

> That provider is then responding again, after a couple of hours, when the auto-better task runs, and auto-better takes the now better subtitle. 

This makes no sense because if it didn't grab a subtitle then there wouldn't be duplicated subtitles showing in plex

> Also make sure that there's only SZ subtitles in the media folder for a given media item, otherwise Plex may display duplicate subtitles.

I have subzero currently set to store it as metadata, and there isn't any other subtitle other than the embedded PGS stuff.

**Comment by pannal** [comment] 2017-09-01 07:38
> This makes no sense because if it didn't grab a subtitle then there wouldn't be duplicated subtitles showing in plex

Sure it makes sense. It grabs a subtitle with a score X from provider A, later finds a subtitle with the better score Y on provider B, which was not responding at the initial run.

**Comment by pannal** [comment] 2017-09-01 07:41
Ah, I was referring to `Sometimes it downloads subtitles twice.` and what you see in the history tab (auto-better). So this is about duplicate subtitles displayed in the Plex clients?

Do you have other subtitle agents enabled?

**Comment by Nottt** [comment] 2017-09-01 08:14
Sorry I should have been clearer yes, I have duplicated subtitles displayed in plex clients. And no I don't have any other agents enabled. 

How can I bulk-scan the Plex metadata folder? I've been thinking and use that option to make subzero to store all subtitles in a custom path so it will easier to manage, will subzero move subtitles or download all again? What if I then move the subs from there to next to my media files?

**Comment by pannal** [comment] 2017-09-01 23:40
There's a very slim chance that you can move the metadata subtitles next to your media files and have them recognized. The subtitle files stored by plex inside the metadata folder are hash-based, and if you don't do some massive digging you won't be able to.

You have the option to set SZ to a global subtitle folder and have it download everything to that folder, again.

**Comment by Nottt** [comment] 2017-09-01 23:50
Ok thanks for the support. Is there anything we can do to know why subzero
is still duplicating my subtitles ? :/

**Comment by pannal** [comment] 2017-09-02 00:01
You can set SZ's log level to DEBUG, disable multi processing (`Search enabled providers simultaneously (multithreading)`), then try to trigger the bug again. When you triggered the bug, please attach the [log zip](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs#sub-zero-channel-is-accessible).

**Comment by Nottt** [comment] 2017-09-03 09:31
I've set it for DEBUG and have it let run for some time, I'm not sure it duplicated subtitles again but it did scan, most of my files are displaying multiple external subtitles..especially the last files so I hope that helps!

Also I noticed subzero is only periodically scanning for new subtitles in 1 library and not all? Is there a way to make it run for all of my libraries ?

Thanks so much for the support !

[Logs_170903_11-23-45.zip](https://github.com/pannal/Sub-Zero.bundle/files/1272820/Logs_170903_11-23-45.zip)

**Comment by Nottt** [comment] 2017-09-05 09:07
I caught it on act : 

https://imgur.com/a/8fJUr

My logs : 

[Logs_170905_08-43-12.zip](https://github.com/pannal/Sub-Zero.bundle/files/1276756/Logs_170905_08-43-12.zip)

**Comment by pannal** [comment] 2017-10-11 00:48
Sorry for the long delay. I'll investigate again, once I have the time.

**Comment by Nottt** [comment] 2017-10-18 13:46
No issues. This is happening again on a fresh plex install in a totally different new environment (docker). It's not downloading 2 VTT subtitles for each movie and one SRT. I'm tempted to just make a script that watch my folder for duplicated files and then delete them...

**Comment by pannal** [comment] 2017-10-18 14:07
What I can see from your logs is: DownloadLimitReached for OpenSubtitles, and you don't have unrar installed (please do that).

Also please set Scan to `strict`.

And the new version with some fixes should arrive on your PMS soon, it got accepted today.

**Comment by Nottt** [comment] 2017-10-18 14:39
Scan is set to strict, subtitles are still downloading. And I do have unrar installed on host, I'm not sure inside the container... 

No I'm storing it in the same folder as my media.

**Comment by pannal** [comment] 2017-10-18 15:26
The "Scan" option only determines, how local subtitle files are matched for a certain media item. It has no effect on what's downloaded or found online. Please set it to strict for now.

Also some issues with duplicate subtitles have been resolved in the latest version (2.0.26.1715).

**Comment by Nottt** [comment] 2017-10-19 03:37
Thanks pannal, do you believe this is a subzero issue then? I was about to ask about this in the plex forums...

also I'm on Sub-Zero 2.0.26.1715 version already.

**Comment by pannal** [comment] 2017-10-19 21:55
This should not happen anymore with 1715 and the correct settings. You need to refresh the library metadata, so SZ rescans the existing subtitles and updates your subtitle dropdown for the older items. It shouldn't happen with newly added items!

**Comment by Nottt** [comment] 2017-10-19 22:28
Like I said this is a fresh install of Plex, with latest subzero and I
didn't had any subs before. I installed subzero, configured it and then
added my library from 0 and let it scan it and refresh subs

At least it's not giving me 7 duplicated subs like before, only 2 vtt
subtitles.

But they aren't duplicated on disk. I'm going to edit this later with
printscreen of all my settings. I changed them to as you said and I've
already refreshed my metadata multiple times.

**Comment by Nottt** [comment] 2017-10-20 10:17
When I refresh the data again, the duplicated entry is removed, but all first metadata build will generate a duplicated entry for now.

**Comment by pannal** [comment] 2017-10-20 10:57
OK, does this only happen with the VTT subs?

**Comment by Nottt** [comment] 2017-10-20 11:05
Yes. Only for vtt subs.

**Comment by Nottt** [comment] 2017-10-21 06:34
```Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
GUI: Requesting metadata for 'Annabelle: Creation' 

/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/subtitle.py:349: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if video.title and 'title' in guess and sanitize(guess['title']) == sanitize(video.title):
```

Found those interesting output in my stderr logs of my plex container today.

**Comment by Nottt** [comment] 2017-10-28 13:25
@pannal any attention to this issue ? :( It keeps happening with me and now it seems to be getting worse...I can give you access to anything you need :(

**Comment by pannal** [comment] 2017-10-28 23:35
I'm pretty uncertain why this happens. I've got a suspicion, though. 

Please go to your plex web interface, open an item that has duplicated subtitles, then paste the `key=%2Flibrary%2Fmetadata%2FXXXXXX` portion from the URL here.

Then can you get me your `~/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db` file after stopping the PMS?

**Comment by Nottt** [comment] 2017-10-29 09:09
@pannal  

URL = `key=%2Flibrary%2Fmetadata%2F4227`

File was scanned with no external or embedded subtitles.  Showing 2 VTT subtitles, 

URL `key=%2Flibrary%2Fmetadata%2F4224` 

File was scanned with one subtitle ending with .por.srt and results in two SRT files in the filesystem ( one .por. and one .pt-BR ) and 1 ghost VTT subtitle. 

URL = `key=%2Flibrary%2Fmetadata%2F4222`

This file was inputted with one embbeded PGS subtitles and one external .SRT, ended up with 2 SRT files because of that naming issue above again, but just 1 VTT subtitle as expected. 

URL = `key=%2Flibrary%2Fmetadata%2F4221`

File had a embedded SRT subtitle but it still downloaded new subs, and I have it set to don't download if existing. File also shows 1 ghost VTT subtitle. 

I thinks this cover all the use cases, here is the [database ](https://mega.nz/#!wyBR0SDC!N3ELq00sexTAeVTAvZ-Vdr3Va59naTiqbtGiZlL822Y) 



Then I went and manually forced a metadata refresh in all of the above itens which removed all the duplicates, here is the database file and a debug log of SubZero after performing this action .

[Logs_171029_09-03-09.zip](https://github.com/pannal/Sub-Zero.bundle/files/1424892/Logs_171029_09-03-09.zip)

[Fixed database] (https://mega.nz/#!V2BSCYgQ!gbwjwm5qSSxrO6NDOz623pKpvXq47tQl5EXpdSXtcvQ)

I hope i'm doing this debugging thing well, if you need anything else let me know...

**Comment by pannal** [comment] 2017-10-29 13:02
Found it. It's a problem related to how the PMS LocalMedia package picks up VTT files. I've reported it to the Plex guys. In the meantime I've "dumbed down" SZ's VTT handling, which should circumvent the duplication issue.

As for the internal subtitle not being taken into account while determining whether to search for a new one: do you have `Treat IETF language tags as ISO 639-1 (e.g. pt-BR = pt)` on?

**Comment by Nottt** [comment] 2017-10-30 09:40
No I don't, but I'll see if I can upgrade.

Also it's not only searching for new ones when a subtitle already exists, but also deletes the ones I already have... Even .forced.lang named subtitles are being deleted too, which is bad because I often have external forced subs that already comes with the file. However this doesn't seem to happen all the time... I have no idea why. 

![roxel2t](https://user-images.githubusercontent.com/13532436/32163623-07a9a2ee-bd44-11e7-83c3-5e81ca3b16ee.png)
![t27ruwu](https://user-images.githubusercontent.com/13532436/32163631-0bd4a134-bd44-11e7-91be-18265924d6c2.png)
![u9xrsdb](https://user-images.githubusercontent.com/13532436/32163634-0ccd17d8-bd44-11e7-985e-36ee11ebda3a.png)
![rxn69ft](https://user-images.githubusercontent.com/13532436/32163638-0ddb791c-bd44-11e7-8136-572bf345151c.png)

Also glad to hear the VTT issue is fixed and I could help that happen.

**Comment by pannal** [comment] 2017-10-30 09:47
Well for starters you can turn off the automatic leftover subtitle function.

If it's enabled, SZ cleans up subtitle files that don't match any current media _filename_. So if there's `Peter.Parker.mkv` and `Peter Parker.en.forced.srt`, it'd kill it, as `Peter.Parker` isn't inside `Peter Parker`.

Also currently the cleanup function does not take `exact` or `loose` into account.

**Comment by Nottt** [comment] 2017-10-30 10:04
Oh okay thanks, is there any plan to take forced subtitles in consideration in this behavior? Why SubZero doesn't already support forced-only and mixed subtitles? This also happens if it's .por. instead of .pt-BR. 

I also just noticed that I had `I keep the exact (release-) filename of my media files` enabled but I don't. 

I use this naming schemes for radarr/sonarr 

`{Series CleanTitle} - S{season:00}E{episode:00} - {Episode CleanTitle} {[Quality Full]} {[MediaInfo_Full]} {[Release Group]}`

`Single Episode Example : The Series Title 2010 - S01E01 - Episode Title 1 [HDTV-720p Proper] [x264_DTS_[EN+DE]] [RlsGrp]`

For movies :

`{Movie CleanTitle} ({Release Year}) {[Edition Tags]} {[Quality Full]} {[MediaInfo Full]} {[Release Group]}`

`Example : The Movie Title (2010) [Ultimate Extended Edition] [Bluray-1080p Proper] [x264 DTS [EN+DE]] [EVOLVE]`

When I manually do this I usually do plex standard [quality] [audio tracks(PT+EN]] [GROUP].

Also...wtf is this ?

![subzero](https://user-images.githubusercontent.com/13532436/32164898-ff0b4ad0-bd47-11e7-8125-ebde4cbb359c.png)

What is the best way to remove subzero cleanly and install your develop version?

**Comment by Nottt** [comment] 2017-10-30 10:37
@pannal thanks buddy, for your awesome work! But I'm not sure how I stop plex inside the container? I'll see if the plugins folder is exposed to me, if so I probably can just stop the container, replace it and start it again right? 

What do you mean can't search multiple subtitles? You already have a option to search for 4 languages at same time.

**Comment by pannal** [comment] 2017-10-30 10:39
Yes, but not different kinds per language. 

I don't know how you can stop Plex inside the container, but stopping the container should work as well.

**Comment by Nottt** [comment] 2017-10-30 11:15
@pannal  I'm on Sub-Zero 2.0.28.1740 DEV now, will observe the behavior and report back if any bug happens again, you can close this issue if you want, I'll post if anything happens.

Thanks for the support! I already became a patreon :)

**Comment by pannal** [comment] 2017-10-30 11:28
Thank you :)

**Comment by Nottt** [comment] 2017-10-30 14:09
@pannal I have a issue now that it won't download new subs for new files. My log is full of entries like :

```
2017-10-30 13:11:14,999 (7f360492f700) :  INFO (logger:30) - subliminal.core: Downloading best subtitles for <Episode [u'Dragon Ball Super', 2015, 2x6]>
2017-10-30 13:11:14,999 (7f360492f700) :  INFO (logger:30) - subliminal_patch.core: Skipping provider 'legendastv': no language to search for
2017-10-30 13:11:15,000 (7f360492f700) :  INFO (logger:30) - subliminal_patch.core: Skipping provider 'tvsubtitles': no language to search for
2017-10-30 13:11:15,000 (7f360492f700) :  INFO (logger:30) - subliminal_patch.core: Skipping provider 'opensubtitles': no language to search for
```
[Logs_171030_09-58-34.zip](https://github.com/pannal/Sub-Zero.bundle/files/1427465/Logs_171030_09-58-34.zip)

Should I open a new issue?

**Comment by pannal** [comment] 2017-10-30 16:02
I can't find that example inside your logs. Can you give me an example?

**Comment by Nottt** [comment] 2017-10-30 16:04
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1427882/com.plexapp.agents.subzero.log)

Here, I don't know what happened with the logs I uploaded...

**Comment by pannal** [comment] 2017-10-30 16:08
Yep, I think I got it. Uploaded a fix to develop-2.0.

**Comment by Nottt** [comment] 2017-10-30 16:13
You're quick dude! going to test it soon again. Have streams going on now... thanks!

**Comment by pannal** [comment] 2017-10-30 16:37
I'm not sure if my current approach solves the pt-BR problem. But you'll tell me :)

**Comment by Nottt** [comment] 2017-10-30 21:29
@pannal now the file that had only PGS eng subs downloaded subtitles, but now it seems opensubtitles is broken lol and a bunch of strange erros like about permissions and a performance hit for not being able to decode something ?

I don't know if I was clear, but before SubZero wasn't downloading subs to any files, even if they only had english PGS subs...

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1428853/com.plexapp.agents.subzero.log)

Thanks! :)

**Comment by pannal** [comment] 2017-10-30 21:58
Is this an issue or is this now expected behaviour? I can't really make that out.

**Comment by Nottt** [comment] 2017-10-31 12:47
@pannal  Yep I mean about this simplejson thing...

And I have no idea of how the world inside the docker is running, but there shouldn't be any change with a simple docker stop and start to replace subzero.

I even did chown user:user -R . on the plex folder that is exposed to the host.

**Comment by pannal** [comment] 2017-10-31 15:27
So is everything working as expected?

**Comment by Nottt** [comment] 2017-11-06 08:52
Issues seems to have been fixed. Thanks ! If anything happens I ping you again

**Closed** 2017-11-06 10:02 UTC
Labels: 2.0, bug, enhancement
