### ISSUE TITLE
Legendas.tv issues

### ISSUE THREAD

**Issue by samuelblopes** [pannal/Sub-Zero.bundle#596] opened 2018-11-14 19:13 UTC
Hello everyone,
I have been trying to to configure legendas.tv provider and i cant get it to work. Logs just say "2018-11-14 19:10:55,813 (7f7326ffd700) :  INFO (logger:38) - subliminal_patch.core: Skipping provider 'legendastv': no language to search for". Languages to search are defined as pt, pt-br and en, user and password for legendas.tv are set and provider is marked as enabled.

Any tips on what am i missing?

**Comment by howzito** [comment] 2018-11-17 21:01
I am having the same problem, it was working last week and it stopped. Using Windows 10, latest Plex server and subzero. Here are the full log with DEBUG and only one episode on the other file.

Config file is also attached.



[subzero_legendastv_problem.txt](https://github.com/pannal/Sub-Zero.bundle/files/2592248/subzero_legenda
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2592251/com.plexapp.agents.subzero.log)
stv_problem.txt)
[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/2592253/com.plexapp.agents.subzero.txt)

**Comment by pannal** [comment] 2018-11-19 16:00
I can confirm that legendas is broken since 2.6. Fix incoming soon.

**Comment by pannal** [comment] 2018-11-19 16:10
@howzito your issue is different, but will be fixed in the upcoming version, as well.

**Closed** 2018-11-19 16:14 UTC
Labels: 2.6, bug, fixed in upcoming version

**Comment by samuelblopes** [comment] 2018-11-19 17:36
I'm new to Plex so this is probably a stupid question. Sub-zero was installed using Plex itself but since they are removing Plug-ins do i need to manual update?

**Comment by pannal** [comment] 2018-11-19 21:39
No, the update service still works, if you installed it normally.
