### ISSUE TITLE
[Feature suggestion] Auto-sync subs

### ISSUE THREAD

**Issue by Coggi** [pannal/Sub-Zero.bundle#667] opened 2019-09-03 15:36 UTC
Hi,

don't know if this has been ever proposed but I did a quick search and it seems not.

Saw this project here on github -> https://github.com/smacke/subsync

It seems cool and could maybe be included in subzero?

Thank you!

**Comment by pannal** [comment] 2019-09-03 16:13
Duplicate of #644

**Closed by pannal** 2019-09-03 16:13 UTC
