### ISSUE TITLE
Erroneous "Log.Warning" calls (should be Log.Warn) causes plugin crash

### ISSUE THREAD

**Issue by mikeclueby4** [pannal/Sub-Zero.bundle#633] opened 2019-04-13 12:19 UTC
I've been bitten by Sub-Zero not downloading anything whatsoever since march. Finally figured it out.

![image](https://user-images.githubusercontent.com/16208265/56079585-20328d80-5df7-11e9-881c-d2ea7be95a51.png)

There is no ".Warning()" method on "Log", only "Warn()".

**Comment by pannal** [comment] 2019-04-13 13:55
Duplicate of #629 #619

**Closed** 2019-04-14 10:45 UTC
Labels: 2.6, duplicate, fixed in upcoming version
