### ISSUE TITLE
Why does my Sub-Zero channel have a "red" makers in it's gfx ?

### ISSUE THREAD

**Issue by stve-a** [pannal/Sub-Zero.bundle#367] opened 2017-10-21 07:42 UTC
Don't know since when this started, since I'm not looking at my channels alot.

![image](https://user-images.githubusercontent.com/11457252/31849526-124b68ba-b644-11e7-8c9a-8769d71556d1.png)

Anyone know why this is ? I tried to google it or see if it is something that plex does with out of date channels or something, but could not find anything and afaik the sub-zero channel is not outdated ?

I'm running Sub-Zero 2.0.26.1715

**Comment by pannal** [comment] 2017-10-21 08:40
This is intended behavior to warn you about the fact, that you're missing permissions. It should say so when you enter the channel, also.

**Comment by stve-a** [comment] 2017-10-21 09:23
Hi, 
Thanks for the info @pannal 
I am running PMS on Nvidia Shield TV so yeah permissions are limited.
I do not get any message when entering the channel though.

**Comment by pannal** [comment] 2017-10-21 09:42
Ok then my implementation is incomplete :) 
You did turn off permission warnings I guess?

**Comment by stve-a** [comment] 2017-10-21 09:51
@pannal  "Check for correct folder permissions of every library on plugin start" is enabled.
I guess if I disable it, I don't get the red marker ?
I think everything is running fine though, I still get my subs downloaded.

**Comment by katseassavvas** [comment] 2017-10-22 05:52
Same here. Permission warnings are on, icon appears crossed out with red and no message about permissions. I'm running Plex on a Windows 10 machine, if that helps. Which folder permissions should we fix?

**Comment by pannal** [comment] 2017-10-24 11:21
@stve-a @katseassavvas can you attach logs, please? Trying to reproduce the issue.

**Comment by Nottt** [comment] 2017-10-30 10:12
I'm seeing the same image...somehow... I'm running subzero in docker and writing to a unionfs system, so the layers above subzero take care of making sure permissions are correct, and if I had any issue my entire system would break by now...which didn't happened so something else must be happening?

**Comment by pannal** [comment] 2017-10-30 10:23
Yeah, I'll remove the functionality again, it's unreliable (as expected).

**Comment by pannal** [comment] 2017-10-30 10:25
Fixed in latest develop-2.0.

**Comment by zucram** [comment] 2017-10-30 12:03
I'm on windows 10, how do i fix the permissions problem?

**Comment by pannal** [comment] 2017-10-30 12:11
@zucram there most likely isn't any permission problem, if you enter the SZ menu and get no warning. The current release has buggy detection for the icon.

**Comment by zucram** [comment] 2017-10-30 12:12
Oh ok, yeah i get no warnings and the plugin seems to work fine.

**Comment by pannal** [comment] 2017-11-03 23:46
Should be gone with the newest version

**Closed by pannal** 2017-11-03 23:46 UTC
