### ISSUE TITLE
OpenSubtitles username/password doesn't seem to be used

### ISSUE THREAD

**Issue by fabioneves** [pannal/Sub-Zero.bundle#295] opened 2017-05-28 12:05 UTC
Looks like opensubtitles username/password is not being used, it's giving me an error that the download limit was reached but this is wrong since I can go to the OpenSubtitles website and still download subtitles, I'm a VIP user.

> 2017-05-28 13:00:31,898 (33fc) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles', Traceback: Traceback (most recent call last):
  File "C:\Users\fneves\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 103, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "C:\Users\fneves\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\opensubtitles.py", line 225, in download_subtitle
    response = checked(self.server.DownloadSubtitles(self.token, [str(subtitle.subtitle_id)]))
  File "C:\Users\fneves\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\opensubtitles.py", line 283, in checked
    raise DownloadLimitReached
DownloadLimitReached

Any more info needed?
Using version: Sub-Zero/2.0.20.1364-dev RC9

**Comment by pannal** [comment] 2017-05-30 11:27
Do your server and your PC share the same IP?

**Comment by fabioneves** [comment] 2017-05-30 11:29
Yes, I've tested with 1.4.x without the username/password and I get the downloadlimit message, when I've set the username/pw, it worked fine.

Looks like 2.x doesn't use user details on opensubtitles.

**Comment by pannal** [comment] 2017-05-30 11:39
Yeah there have been a ton of changes in 2.0. I'll check it out.

**Comment by fabioneves** [comment] 2017-05-30 11:41
Cool, thanks! I would like to use 2.0 because of LegendasTV provider.
Btw, is there anyway to trigger only the subtitle routine in Plex, without refreshing the entire metadata?

**Comment by pannal** [comment] 2017-05-30 11:45
No, not really. It always involves refreshing, because otherwise the PMS wouldn't always reliably pick up the changed data (subtitles). I've tried fiddling around with that time and time again, but haven't gotten to any solution yet.

**Comment by fabioneves** [comment] 2017-05-30 11:47
Ok, thanks! I'm basically using plex just because of your plugin. I don't use plex at all.
Thanks a lot for the time you've put into it.

**Comment by pannal** [comment] 2017-05-30 11:48
Ah. Care to join our slack so we can talk about that use case?

**Comment by fabioneves** [comment] 2017-05-30 11:52
Sure! Let me find your slack link.

**Comment by pannal** [comment] 2017-05-30 11:55
Just updated my last post :)

**Comment by pannal** [comment] 2017-05-30 12:53
OK I can confirm that this is not the case. OpenSubtitles API only works with a valid login token and SZ is using that.

@opensubtitles may this be related to #277?

**Comment by pannal** [comment] 2017-05-30 13:06
He's a VIP and gets DownloadLimitReached errors, but still can download via the website.

**Comment by opensubtitles** [comment] 2017-05-30 17:27
whoever have this problem, please send me email directly to admin [at] opensubtitles . [org] and I will look into it.

**Comment by pannal** [comment] 2017-06-23 21:44
Closing for now.

**Closed by pannal** 2017-06-23 21:44 UTC
Labels: 2.0, bug
