### ISSUE TITLE
Captions stop during execution

### ISSUE THREAD

**Issue by rb0rges** [pannal/Sub-Zero.bundle#364] opened 2017-10-17 18:29 UTC
Good!
It is happening regularly of the legend to stop the execution of the series.
[Logs_171017_16-18-56.zip](https://github.com/pannal/Sub-Zero.bundle/files/1392124/Logs_171017_16-18-56.zip)

And could you check if there is something wrong in my settings, to get pt-BR subtitles?
![imagem 001](https://user-images.githubusercontent.com/5033955/31682258-50f0090c-b358-11e7-8731-971a7b77168b.png)
![imagem 002](https://user-images.githubusercontent.com/5033955/31682259-511c0732-b358-11e7-8695-01f05d2f8539.png)
![imagem 003](https://user-images.githubusercontent.com/5033955/31682262-514b82dc-b358-11e7-9aa1-abb380d4c7e7.png)
![imagem 004](https://user-images.githubusercontent.com/5033955/31682263-51749fc8-b358-11e7-9ded-b3b9f6bf8efa.png)
![imagem 005](https://user-images.githubusercontent.com/5033955/31682264-51a15ff4-b358-11e7-8540-2a83f7238b49.png)
![Uploading Imagem 006.png…]()

**Comment by rb0rges** [comment] 2017-10-26 14:39
@pannal 
Are the settings correct to avoid this error?

**Comment by pannal** [comment] 2017-10-26 14:59
The settings are fine.

Your media naming isn't. Please include the format (HDTV, BluRay, ...) and ideally the release group inside the media file names. Alternatively you can lower your TV score to 330 to receive subtitles, but they might not match your specific release.

I don't know what you mean by `It is happening regularly of the legend to stop the execution of the series.`, though.

**Comment by rb0rges** [comment] 2017-10-26 16:13
I do not change the filename, it looks the same as I downloaded it. With writing in formats (HDTV, BluRay, ...).

In the log you could not identify the error of the captions stopped being displayed during the execution of the media?
Well that's what happens, especially when I'm using plex via 'https://app.plex.tv/desktop', at certain times it stops showing and comes back when I click to rewind the media in 10 seconds. With this, it appears that it reloads the caption and resumes display.

**Comment by pannal** [comment] 2017-10-27 07:45
No, as it's not a Sub-Zero issue. #357 is a duplicate of this.

Look here: https://forums.plex.tv/discussion/comment/1535240/#Comment_1535240
https://www.reddit.com/r/PleX/comments/78ppvq/subtitles_work_perfectly_but_they_dissapear_after/

Official reply: http://forums.plex.tv/discussion/comment/1540548/#Comment_1540548

**Comment by rb0rges** [comment] 2017-10-27 13:56
Ok, thank you.

**Comment by rb0rges** [comment] 2017-11-01 11:50
Dear @pannal !
See in this attached video, that in the execution of the video around 11 minutes and 28 seconds the caption stopped working. And it only came back and continues normally when I select another legend. And from what I see there was no legend error with more than 2 lines.
Can you explain the reason for this error, if it is SZ or Plex?

Thank you.

[Rodrigo2017-11-01 09.37.zip](https://github.com/pannal/Sub-Zero.bundle/files/1433988/Rodrigo2017-11-01.09.37.zip)

**Comment by rb0rges** [comment] 2017-11-01 11:51
Follow the log
[Logs_171101_09-50-59.zip](https://github.com/pannal/Sub-Zero.bundle/files/1433997/Logs_171101_09-50-59.zip)

**Comment by pannal** [comment] 2017-11-01 14:09
Yes, as far as I know it's a Plex issue. Please report this on their forums or file a bug report.

**Comment by rb0rges** [comment] 2017-11-01 14:39
Ok, thank you.
https://forums.plex.tv/discussion/294159/captions-stop-executing

**Closed** 2017-11-01 14:39 UTC
