### ISSUE TITLE
Memory usage high

### ISSUE THREAD

**Issue by nnleaf** [pannal/Sub-Zero.bundle#420] opened 2018-01-03 08:37 UTC
I've noticed over the past few weeks my plex server has been eating up a lot of ram. I bumped my VM's ram to 8gb but even that wasn't enough, it eventually went into swap. Library scans got incredibly slow as well. I uninstalled subzero and ram usage instantly went down. 

I would like to help, but I'm unsure what files on my part would be needed to figure out what's going on?

**Comment by pannal** [comment] 2018-01-03 13:14
Yeah I've seen that in the past at two instances. I was never able to pinpoint the cause for this as I can't reproduce it. It seems to only affect a handful of people on a very specific system configuration.

**Comment by mmgoodnow** [comment] 2018-01-03 21:13
Did the library scans improve as well after uninstalling SZ?

**Comment by nnleaf** [comment] 2018-01-04 06:10
Hi, library scans improved right away after uninstalling SubZero. Ram usage also went right back down. I reinstalled SubZero today to test it out and so far it's.. okay. Memory is shown as 5.5g used with 2.1g in buff/cache. I'll update if I notice slowdowns again. 

@pannal I'm running Debian 9.3 in ESXi if that helps. Any information needed, feel free to ask. :)

**Comment by pannal** [comment] 2018-01-04 14:12
Library scans are bound to take longer when SZ is enabled, as it has to scan the actual files on disk and do a whole bunch of other stuff. There have been changes in 2.1 beta that improve the agent's performance, though.

As for  the memory issue:
My SZ instance for example has 400mb reserved and 2,3gb virtual memory allocated - those should be the numbers we're after. The 5.5/2.1g you're experiencing are way too high.

Is there anything you might do with SZ that's unusual? Like using specific providers more often than other users, use scraping providers like Addic7ed or Podnapisi heavily? Where's the bulk of your subtitles coming from, and do you have an unusually big library sizes perhaps?

As this issue is hard to debug right now, any small piece of information might help.

**Comment by pannal** [comment] 2018-01-04 16:15
Can you post a log right after the restart of the plugin? (Advanced menu -> restart plugin)
Does `Invalidate Sub-Zero metadata caches (subliminal)` in the advanced menu clean up the memory?

**Comment by pannal** [comment] 2018-01-04 17:10
OK I might have something. Tell me there's `dbm_supported: False` in there and I'll know where to look.

**Comment by pannal** [comment] 2018-01-05 02:43
@nnleaf please [join the 2.1 beta](https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes) so we can test this, I think I may have found what's causing this.

**Comment by shocker2** [comment] 2018-01-13 19:45
Hi, I'm heaving the same issue with Sub-Zero v2.0.33.1871. This process Plex Plug-in [com.plexapp.agents.subzero] is eating up my entire ram, it's going up to 12GB. After a SZ restart the RAM is going to 0 and in few hours it's increasing again.
I'm using the latest CentOS v7 with the latest PMS Beta.
In the logs I can see that I have: "DEBUG (menu:214) - config.dbm_supported: False".
Is this fixed in the v2.1 beta?

**Comment by pannal** [comment] 2018-01-13 21:35
Not confirmed by any third party, but I think I found and fixed the issue. Please test 2.1 beta by following the link in my previous comment.

**Comment by shocker2** [comment] 2018-01-14 02:19
Thank you for the feedback! Upgraded to v2.1 and in 20 min the ram is almost 4.5GB and it's still increasing, don't think that the issue was solved. 
4546.61 MB 12481                Plex Plug-in [com.plexapp.agents.subzero]

**Comment by pannal** [comment] 2018-01-14 03:57
Damn. I believe common memory issues have been resolved with 2.1, but I've never been able to reproduce these extreme versions of them. Judging from previous bug reports, you're most likely one of 10 people in 50.000 who have this currently.

I'd love to see [DEBUG logs](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs) (set SZ's log level to DEBUG in SZ's settings before that), perhaps I can spot something obvious.

**Comment by shocker2** [comment] 2018-01-14 21:22
Seems to be 2.1 according to the log:
2018-01-14 03:49:15,197 (7f58a8d20740) :  DEBUG (menu:234) - config.dbm_supported: False
2018-01-14 03:49:15,200 (7f58a8d20740) :  DEBUG (menu:256) - Platform: Linux-i386
2018-01-14 03:49:15,200 (7f58a8d20740) :  DEBUG (menu:257) - OS: Linux
2018-01-14 03:49:15,200 (7f58a8d20740) :  DEBUG (menu:258) - Python: 2.7.12
2018-01-14 03:49:15,202 (7f58a8d20740) :  DEBUG (menu:267) - SZ_USER_AGENT: Sub-Zero/2.1.0.15-dev
I will re-enable the plugin in debug to capture the logs tomorrow.

**Comment by nnleaf** [comment] 2018-01-16 07:17
@shocker2 
Wow, I had 2k files, 600mb of files in there. 
Deleted them all, restarted subzero and memory usage seems to be under control. I'll check again tomorrow to see how it's going.

**Comment by pannal** [comment] 2018-01-16 11:13
Has any of you moved the old data somewhere instead of deleting it? Otherwise you've helped no one but yourselves.

It's normal that you have that many subtitle storage files inside that folder, depending on the size of your library. The solution is to find which ones cause the memory leak and why.

After deleting all of them SZ now has no previous information about the subtitles inside your libraries anymore, the tasks won't work as expected and the menu will show "no current subtitle in storage" for every media item.

**Comment by shocker2** [comment] 2018-01-16 12:29
Just deleted them, sorry :(

**Comment by pannal** [comment] 2018-03-17 23:42
Closing this for now. Please reopen if issue reappears!

**Closed by pannal** 2018-03-17 23:42 UTC
Labels: 2.0, beta, bug, enhancement
