### ISSUE TITLE
Sub-Zero stopped working after Plex update

### ISSUE THREAD

**Issue by n-halder** [pannal/Sub-Zero.bundle#665] opened 2019-08-21 04:33 UTC
SubZero 2.6.5.3124 not opening after upgrading Plex Media Server from version 1.16.3.1402 to 1.16.5.1488. Works fine with the previous version of Plex.

My OS: Windows 7 Professional with the latest updates.

[https://streamable.com/xk4pj](url)

**Comment by nismanoke** [comment] 2019-08-21 18:53
Hi,

i have the same problem (Plex Version 1.16.5.1488; Sub-Zero 2.6.5.3124) and added my log file. It shows the error below at the bottom of the file. Hope for a quick fix.

`ERROR (model:205) - Cannot read model from /config/Library/Application Support/Plex Media Server/Metadata/TV Shows/6/87581213b8c5c39f87fa27bc7c7826f43a5a0e5.bundle/Contents/com.plexapp.agents.subzero
2019-08-21 20:34:49,440 (1551ea2ad700) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: No show id found for u'Two and a Half Men' ({'year': 2003})
2019-08-21 20:34:49,629 (1552194c3700) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'titlovi': Traceback (most recent call last):`

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3526822/com.plexapp.agents.subzero.log)

**Comment by azah** [comment] 2019-08-22 05:41
I get the same issue.
```
2019-08-22 00:48:09,947 (7f51d5ffb700) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: No show id found for 'Running Man' ({'year': 2010})
2019-08-22 00:54:08,947 (7f51a35e7700) :  ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/f/7fac0332092155f7d46df0c4a0c79da2bd30245.bundle/Contents/com.plexapp.agents.subzero
2019-08-22 00:54:12,356 (7f51d5ffb700) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: No show id found for u'The Simpsons' ({'year': 1989})
```

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3528435/com.plexapp.agents.subzero.log)

**Comment by azah** [comment] 2019-08-22 05:51
Here's the `Info.xml` in the directory it tried to access:
`cat 7fac0332092155f7d46df0c4a0c79da2bd30245.bundle/Contents/com.plexapp.agents.subzero/Info.xml`
```xml
<?xml version='1.0' encoding='utf-8'?>
<TV_Show id="null">
  <rating/>
  <title_sort/>
  <art/>
  <themes/>
  <posters/>
  <duration/>
  <genres/>
  <title/>
  <rating_count/>
  <collections/>
  <tags/>
  <audience_rating_image/>
  <rating_image/>
  <audience_rating/>
  <studio/>
  <seasons/>
  <originally_available_at/>
  <roles/>
  <countries/>
  <content_rating/>
  <original_title/>
  <summary/>
  <reviews/>
  <banners/>
  <similar/>
</TV_Show>
```

**Comment by pannal** [comment] 2019-08-22 12:38
All of this is a duplicate of #655.
@nismanoke @azah the "cannot load model from" isn't an error, it's tagged wrongly and comes from the Plex Framework. It just means that there isn't any info inside the model.

You have to use Kitana now.

@nismanoke your titlovi error is because you don't have an AntiCaptcha provider configured. This will be fixed by implementing their new API in the next SZ update.

**Closed by pannal** 2019-08-22 12:38 UTC

**Comment by azah** [comment] 2019-08-22 13:39
@pannal with kitana, it's no longer possible to get logs from the advanced section.

**Comment by pannal** [comment] 2019-08-22 13:50
Yes I know, that's a bug that will be resolved. For now you'll have to navigate your logs manually
