### ISSUE TITLE
executable upon successful not executing.

### ISSUE THREAD

**Issue by jdalton** [pannal/Sub-Zero.bundle#247] opened 2017-03-03 05:56 UTC
The executable I specified doesn't appear to be executed in Sub-Zero 1.4.22.898.
I checked the log and can't find an error. Is there something that I should be looking for?

The value is:
```text
/share/CACHEDEV1_DATA/test.js %(subtitle_path)s
```
It's an executable Node script.

**Comment by pannal** [comment] 2017-03-03 10:09
Please set SZ to DEBUG, try again, then zip up all of your SZ logs and attach them here. Thank you :)

**Comment by jdalton** [comment] 2017-03-06 05:18
Never mind, I spotted the error in the logs. Thanks!

**Comment by jdalton** [comment] 2017-03-07 01:27
@pannal btw I noticed that folks have to explicitly specify the executable for known extensions like `.sh`, `/bin/sh /path/to/script.sh`, instead of relying on the shebang, `/usr/bin/env`. Is this a python or implementation limitation?

**Comment by pannal** [comment] 2017-03-07 08:52
I'm not really sure, I'm using `subprocess.check_output` for calling the executables.

Although using the shebang works in my case. I'm using `#!/bin/bash` for testing purposes and have +x on the file. Have you tried `#!/bin/sh` ?

**Comment by jdalton** [comment] 2017-03-08 17:28
Yeah. I suspect it has everything to do with it being a QNAP package. Those packages muck with paths so things get bizarro real quick.

**Comment by ukdtom** [comment] 2017-03-09 01:39
Since I'm kinda into QNAP as well, please upload your script, and I'll take a look

**Comment by pannal** [comment] 2017-03-09 23:45
@jdalton still there?

**Comment by jdalton** [comment] 2017-03-09 23:47
Yes, I wanted to check one more thing before having you all dig into it. I noticed I had overwritten part of my `/opt/etc/profile` which could have affected the path resolution within the QNAP package. Will get back this evening.

**Comment by pannal** [comment] 2017-03-11 02:52
May be related to this: http://stackoverflow.com/questions/6441507/executing-python-scripts-with-subprocess-call-using-shebang

**Comment by pannal** [comment] 2017-03-11 03:00
@jdalton please try the manual installation of https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip (see wiki->dev  on how to do so)

It's now using shell=True and hopefully sane argument escaping to fix your problem.

**Comment by jdalton** [comment] 2017-03-11 06:25
> Edit: You've posted /share/CACHEDEV1_DATA/test.js %(subtitle_path)s % - why the trailing %?

Just a typo in the comment. The real field value doesn't have it.

**Comment by jdalton** [comment] 2017-03-11 09:32
> please try the manual installation of https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip (see wiki->dev on how to do so)
>
It's now using shell=True and hopefully sane argument escaping to fix your problem.

Thanks for the update! The patch is a good thing but doesn't fix the error I'm seeing. I'm curious if @ukdtom  can repro the issue too.

**Comment by pannal** [comment] 2017-03-12 02:50
Can you post the log containing the error you're seeing? The patch in develop-1.4 was intended to resolve your shebang behaviour.

**Comment by jdalton** [comment] 2017-03-16 07:43
QNAP packages like to rewire environment paths which is what I suspect the issue is. The error isn't really helpful:
```
DEBUG (helpers:264) - Calling /share/CACHEDEV1_DATA/test.js with arguments: [u'/share/CACHEDEV1_DATA/video.en.srt']
ERROR (helpers:269) - Calling /share/CACHEDEV1_DATA/test.js failed: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/helpers.py", line 267, in notify_executable
    stderr=subprocess.STDOUT, shell=True)
  File "/data/jenkins/pms-deps-universal-v2/BUILD_TAG/linux-ubuntu-x86_64/output/pms-depends-linux-ubuntu-x86_64-release-a1aa6ed/lib/python2.7/subprocess.py", line 574, in check_output
CalledProcessError: Command '/share/CACHEDEV1_DATA/test.js "/share/CACHEDEV1_DATA/video.en.srt"' returned non-zero exit status 127
```

**Comment by pannal** [comment] 2017-03-16 09:55
Hm yeah,[ according to this](http://stackoverflow.com/questions/1763156/127-return-code-from) 127 means sh didn't find the command in PATH.

And you can circumvent that by specifying the shell in the command line instead of a shebang?

**Comment by jdalton** [comment] 2017-03-16 14:20
> And you can circumvent that by specifying the shell in the command line instead of a shebang?

Yep, if I specify the full path to the executable in the command, then it works.

**Comment by ukdtom** [comment] 2017-03-16 18:34
Haven't tried it yet, since I sadly forgot all about this GHI, so still valid for me to dig into?

**Comment by pannal** [comment] 2017-03-16 22:30
@ukdtom yep, still is.

**Comment by ukdtom** [comment] 2017-03-16 22:33
I hate you :-P

**Comment by ukdtom** [comment] 2017-03-16 22:34
@jdalton What QTS version are you on?

**Comment by pannal** [comment] 2017-03-16 22:35
:_(

**Comment by jdalton** [comment] 2017-03-16 22:36
@ukdtom
> What QTS version are you on?

QTS 4.3.2.0050

**Comment by jdalton** [comment] 2017-03-16 22:38
Plex Version 1.4.0.3224

**Comment by ukdtom** [comment] 2017-03-16 22:39
Sadly forgot here to ask what QNAP model, so I can test with the same QTS version and CPU arch.

**Comment by jdalton** [comment] 2017-03-16 22:42
TS-251+

**Comment by ukdtom** [comment] 2017-03-16 22:48
I was afraid of that.

The only Intel based QNAP I got still on 32bit OS is my production one ( = the one my wife use to watch movies )

But will try, but sadly has to wait a few days, since bedtime now here, and busy with family events the next two days...

Hopefully Sunday ;-)

**Comment by pannal** [comment] 2017-03-25 21:54
How's the progress on this?

**Comment by ukdtom** [comment] 2017-03-25 22:26
Not good, since currently in a disk swapping hell here, but it's not forgotten

**Comment by pannal** [comment] 2017-04-04 15:56
In the environment the script gets executed in, is $SHELL set?

**Comment by pannal** [comment] 2017-05-12 23:35
And is the file in question with unix EOLs? Windows EOLs tend to skip the shebang. (\r\n)

**Comment by pannal** [comment] 2017-05-12 23:35
@jdalton

**Comment by jdalton** [comment] 2017-05-12 23:37
Unix EOLs.

**Comment by pannal** [comment] 2017-05-12 23:39
Damn. No idea then. Will need @ukdtom for this.

**Comment by pannal** [comment] 2017-05-12 23:46
I think this is an ENV problem. 

Care to try https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip?

**Comment by pannal** [comment] 2017-08-03 17:24
Closing, no answer.

**Closed by pannal** 2017-08-03 17:24 UTC
