### ISSUE TITLE
Error extracting embedded subtitles

### ISSUE THREAD

**Issue by BrutuZ** [pannal/Sub-Zero.bundle#631] opened 2019-04-11 17:17 UTC
Recently noticed that SZ doesn't seem to be extracting embedded subtitles for a while now (given the lack of .en files locally). A quick scan through the log after refreshing a new item (just to avoid additional lines by not having anything on the online providers yet) and the following traceback caught my attention:
```
2019-04-11 13:29:25,450 (1584) :  ERROR (logkit:22) - Extraction failed: Traceback (most recent call last):
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\interface\menu_helpers.py", line 198, in extract_embedded_sub
    output = subprocess.check_output(quote_args(args), stderr=subprocess.PIPE, shell=True)
  File "G:\Plex\python27.zip\subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '"G:\Plex\plex transcoder.exe" -i "G:\Séries\***ANY_FILENAME***.mkv" -map 0:2 -f srt -' returned non-zero exit status 1
```

This happens both on master and develop-2.6 branches, also with slightly older versions of Plex (updated from either 1.13.7.5369 or 1.15.2.793 just a couple days ago)

Full INFO log: https://gist.github.com/BrutuZ/fa3646a2e9805deea3bae33ee6b7c81a

**Comment by pannal** [comment] 2019-04-11 20:14
Interesting. Can you try calling the command manually and see what the output is?

**Comment by BrutuZ** [comment] 2019-04-11 20:27
Outputs the subtitle contents to console "almost" as intended. On Windows at least the console doesn't seem to be able to handle the flow so there's quite a lot of garbage (partial progress indicators, probably updated via Carriage Return) in the middle, piping it to a file or the clipboard returns a clean result.

**Comment by pannal** [comment] 2019-04-11 20:29
Can you make out the return code when running manually? It may actually be 1 even though it works properly.

**Comment by BrutuZ** [comment] 2019-04-11 20:33
`echo %ERRORLEVEL%` indicates return code 0

**Comment by pannal** [comment] 2019-04-11 20:35
Wtf. I'm going to have to try and reproduce this on a windows installation. I'll get back to you.

**Comment by BrutuZ** [comment] 2019-04-11 20:47
Maybe it is interpreting one of the outputs as return?
If I run he above command suffixed with `2>2.log >1.log` then 1.log is filled with the subtitle contents, while 2.log will have the console "diagnostics" output (ffmpeg build version\flags, media file metadata\ToC, operation progress...)

**Comment by pannal** [comment] 2019-04-11 20:49
Hmm it wouldn't really make sense that it does that now, and only on windows (I'm on current PMS on Linux and it's happily extracting away).

Also I believe the return code can't be set by the output.

**Comment by BrutuZ** [comment] 2019-04-11 22:17
Tried running the `subprocess.check_output` in stand-alone Python without the stderr piping, just the encoder and required parameters and the output showed a recurring problem I've experienced with several Plex and Kodi plugins (Python in general) in the past: Unicode characters.

The command is indeed returning an error when run through Python's subprocess because it is not interpreting the `é` character in the media file path correctly. Since the file doesn't exist (it converted `Séries` as `SÔÇÜries` in the python console) the command returns an error code 1.
The Windows console doesn't have this problem, hence the expected error code 0 in the previous test

**Comment by pannal** [comment] 2019-04-11 22:58
Ah OK, I briefly thought about that, but ditched the idea immediately, because SZ handles non-ascii quite well.

Seems like I didn't properly implement it into the extraction process, though. I'll have a fix ready at the weekend and the next release is just around the corner. 

Thanks for testing!

**Comment by pannal** [comment] 2019-04-12 12:53
@BrutuZ can you try the latest develop-2.6 branch? It should be fixed there.

**Comment by BrutuZ** [comment] 2019-04-12 17:46
No luck unfortunately. Still returning the same error after the patch.

**Comment by pannal** [comment] 2019-04-12 22:38
Are you sure you properly updated? With a plugin or PMS restart? My local tests succeeded, maybe I've missed something.

**Comment by BrutuZ** [comment] 2019-04-12 23:26
As far as I can tell. Closed PMS, pulled from GitHub, restarted PMS, clicked "Refresh Metadata" for the item.
https://gist.github.com/BrutuZ/fa5302fe483c3b6d408350b3f47ea639

**Comment by pannal** [comment] 2019-04-12 23:55
Hmm OK. Can you check whether there are any residual .pyc files in the folder? That normally shouldn't matter, but better safe than sorry.

**Comment by pannal** [comment] 2019-04-13 00:33
@BrutuZ pushed a fix. Works for me on Windows.

**Comment by BrutuZ** [comment] 2019-04-13 00:40
That one did the trick, successfully extracted now

**Comment by pannal** [comment] 2019-04-13 00:53
Thank you for reporting!

**Closed** 2019-04-27 22:29 UTC
Labels: 2.6, bug
