### ISSUE TITLE
Plex Transcoder not found, can't auto extract

### ISSUE THREAD

**Issue by saulomarchiori** [pannal/Sub-Zero.bundle#619] opened 2019-02-18 18:59 UTC
Hello!
The plugin is not working for me and some users on Plex Forums after some update a few weeks ago.
I already reinstalled the plugin, but the problem persists. 
Is something that I can do to fix it?

The error is always the same:

```
2019-02-18 14:58:32,180 (5264) :  CRITICAL (core:574) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.6.4.2911)', called with guid 'com.plexapp.agents.thetvdb://343337?lang=pt' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-9311f93fd\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "E:\AppData\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\__init__.py", line 227, in update
    Log.Warning("Plex Transcoder not found, can't auto extract")
AttributeError: 'LogKit' object has no attribute 'Warning'
```

**Comment by DeviDarkL** [comment] 2019-02-24 19:59
Same problem here. Exactly the same error :(

**Comment by davveh** [comment] 2019-03-01 18:40
Same here..

**Comment by ukdtom** [comment] 2019-03-01 19:43
Logs?
(And in a zip)
@davveh @DeviDarkL @saulomarchiori

**Comment by davveh** [comment] 2019-03-01 19:46
[com.plexapp.agents.subzero-190301.zip](https://github.com/pannal/Sub-Zero.bundle/files/2920840/com.plexapp.agents.subzero-190301.zip)

Need any more logs?

**Comment by davveh** [comment] 2019-03-01 22:04
[Logs_190301_23-03-05.zip](https://github.com/pannal/Sub-Zero.bundle/files/2921199/Logs_190301_23-03-05.zip)
here is the full logs

**Comment by davveh** [comment] 2019-03-01 22:12
FYI: the dev version from this github works, so it seems to be fixed in next version.

**Comment by pannal** [comment] 2019-03-02 00:20
@davveh interesting. You're using the develop-2.6 branch and that works?

**Comment by pannal** [comment] 2019-03-02 00:22
@davveh can you tell me where your `plextranscoder.exe` lives in your filesystem?

**Comment by pannal** [comment] 2019-03-02 01:46
#621

**Comment by davveh** [comment] 2019-03-02 17:03
OK, I might have been to quick, it atleast seems to be working better but it doesnt download any subtitles, well, it downloaded 1 and I dont know why :)

[Logs_190302_17-47-26.zip](https://github.com/pannal/Sub-Zero.bundle/files/2922315/Logs_190302_17-47-26.zip)

attaching new logs, i dont have a plextranscoder.exe but a "plex transcoder.exe" in:
C:\Program Files (x86)\Plex\Plex Media Server

Did they maybe change the name in a update of plex?

**Comment by davveh** [comment] 2019-03-02 18:46
OK, Just want to add, I have moved my application data to D: and plex is installed on C:, is that a issue? When i read my last comment it might sound like im rude, im really not, love your work, im just stupid ;)

**Comment by pannal** [comment] 2019-03-02 21:58
@davveh all good, I don't see any rudeness there :)

Browsed through your logs - did you set SZ to development mode? It looks like you didn't and Plex automatically updated your SZ instance to current stable.

You want to follow [this](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation).

Also please download the newest develop-2.6 branch, I've updated the algorithm for finding the plex transcoder. It should find yours now.

**Comment by davveh** [comment] 2019-03-03 16:50
Hey Pannal, I dont think all is OK yet, it works some, might not be related to this issue though but it seems to be using very old information, should I clear something under advanced as well?

When I choose "Items on deck" it shows me stuff that I had there months ago. Not the things I have today. Ran a force to "find better subs", guess its doing it on the whole inventory, I got pretty many movies and series but when checking the "show latest 500 downloaded" there is only 4 subs after abot an hour. After forcing some of the movies on the deck which still didnt have any subs its now showing 6-8 subs in the "latest 500 downloaded".

What ya need? Attaching newest logs.
[Logs_190303_17-50-14.zip](https://github.com/pannal/Sub-Zero.bundle/files/2923353/Logs_190303_17-50-14.zip)

**Comment by davveh** [comment] 2019-03-03 16:52
OK, sorry, I check my logs myself, seems related to:
ConfigurationError: Unsupported language code for subscene: 

I got Swedish and English setup.

**Comment by davveh** [comment] 2019-03-03 18:40
> Hey Pannal, I dont think all is OK yet, it works some, might not be related to this issue though but it seems to be using very old information, should I clear something under advanced as well?
> 
> When I choose "Items on deck" it shows me stuff that I had there months ago. Not the things I have today. Ran a force to "find better subs", guess its doing it on the whole inventory, I got pretty many movies and series but when checking the "show latest 500 downloaded" there is only 4 subs after abot an hour. After forcing some of the movies on the deck which still didnt have any subs its now showing 6-8 subs in the "latest 500 downloaded".
> 
> What ya need? Attaching newest logs.
> [Logs_190303_17-50-14.zip](https://github.com/pannal/Sub-Zero.bundle/files/2923353/Logs_190303_17-50-14.zip)

Ignore the items on deck, that is correct. Only issue I have is that its not downloading anything for me really.. Trying to save the options around some, clear out some options and changing it around abit to see if that helps. Will report back

**Comment by pannal** [comment] 2019-03-04 16:49
@davveh please create a separate issue for no subtitles downloaded. This one has been fixed I guess:
`config.plex_transcoder: C:\Program Files (x86)\Plex\Plex Media Server\plex transcoder.exe`

In your new issue please provide logs, but set SZ to DEBUG mode (`How verbose should the logging be?` in SZ's settings, at the bottom), after refreshing a movie or episode.

**Comment by ChanceGPM** [comment] 2019-03-19 22:20
I can confirm having the same issue and with the same in my logs "("Plex Transcoder not found, can't auto extract")". It is not downloading even though there is subtitles available with over the minimum score. Only way of adding it is doing it manually via the plugin. I'm on latest subzero and latest Plex beta

**Comment by saulomarchiori** [comment] 2019-03-19 22:45
It's working fine in the latest beta. Thank you @pannal

**Comment by dyinggit** [comment] 2019-03-26 14:39
Having the same issue, reverted back my plex update for the time being so that it will still auto download subs.

Thanks for fixing, any idea when the upcoming version is coming out?

**Closed** 2019-04-27 22:29 UTC
Labels: 2.6, bug
