### ISSUE TITLE
Force-Refresh is broken

### ISSUE THREAD

**Issue by JurgendW** [pannal/Sub-Zero.bundle#185] opened 2016-09-17 08:23 UTC
I love the sub-zero plugin. It works great. Sometimes a subtitle with a low score is downloaded and it is out of sync. I can predict from the score which I see from the notification script I built. Any score below 120 is potentially an out of sync subtitle.

When I want to do a "force-refresh" to pull the latest sub-title files it only works sometimes. Most of the times the search is performed. The log file shows it finds subtitles but is does not download any subtitles.

The only way I can make it work is using a file manager, delete the subtitle file and do a " refresh" or "force refresh" again.

This appears to be a bug.

Have attached the log-file with latest occurrence of the problem.
[subzero.log.txt](https://github.com/pannal/Sub-Zero.bundle/files/478046/subzero.log.txt)

**Comment by pannal** [comment] 2016-09-18 21:55
That's very weird. I've never seen it do this before and I can't make out any errors from the log.

Can you spot any familiarities for the items that have this bug? Does it happen for the same items always?

**Comment by JurgendW** [comment] 2016-09-19 17:55
I have attempted to find a few files who exhibit this behaviour. Attached I have added 2 log files: one where the force-refresh is working, one where it is not.

I have tried many more files and have now also captured the file permissions in the attached files. I cannot see anything strange there.

When I had a few files were force refresh worked, I tried the failed one, once more (Suits S06E10). This time the force-refresh worked. It failed 30 minutes earlier.

I cannot make any sense of this behaviour.
[file permissions.txt](https://github.com/pannal/Sub-Zero.bundle/files/480744/file.permissions.txt)
[not working Suits S06E10.txt](https://github.com/pannal/Sub-Zero.bundle/files/480746/not.working.Suits.S06E10.txt)
[working Dark Matter S02E12.txt](https://github.com/pannal/Sub-Zero.bundle/files/480745/working.Dark.Matter.S02E12.txt)

**Comment by pannal** [comment] 2016-10-11 11:44
I've found the problem with the force refreshing. It'll be fixed in the upcoming release.

**Closed by pannal** 2016-10-11 11:44 UTC

**Comment by chopeta** [comment] 2016-10-11 22:58
Hey @pannal, could you describe what the problem is and maybe a workaround that we can use before the fix is released?

**Comment by pannal** [comment] 2016-10-12 07:11
Nope not possible, it's a multi threading issue I just now was able to pinpoint. You can try the master branch manually, though.

**Comment by chopeta** [comment] 2016-10-14 01:05
Thanks for the update @pannal - will keep an eye on the upcoming releases...

**Comment by pannal** [comment] 2016-10-14 01:48
Release is out. Waiting for merge from plexinc.
